### ISSUE TITLE
Automatic reconnect fails after long period disconnected

### ISSUE THREAD

**Issue by alex-gimenez** [eclipse-paho/paho.mqtt.c#1007]
**Describe the bug**
Using the Async API to create a tcp ssl connection to a broker, enabling the auto reconnect feature and letting the system disconnected from the network for some hours (+10h) will prevent the reconnect function to work properly.
This does not happen (or I couldn't reproduce it) with plain tcp connections.

**To Reproduce**
To reproduce it: 
- Connect to an SSL broker. I've tested with AWS and test.mosquitto.org. 
- Enable the automatic reconnect option. Let it connect one time and then just pull out the network cable so that it keeps trying to reconnect.
- After enough time (for me it's been 10-12h) put the cable back in and it will never succeed reconnecting.

I've traced the problem down to MQTTAsync_connecting (see screenshots). There the parameter MQTTVersion is 0, producing that MQTTPacket_send fails without even sending anything over the wire. MQTTVersion should be "4" corresponding to version 3.1.1.
It shouldn't be 0, so somewhere there must be some memory overwrite? I'm not sure when or where it's been reset.

**Expected behavior**
It should always reconnect, no matter how much time it doesn't have connection.

**Screenshots**
![MQTTVersion_0](https://user-images.githubusercontent.com/35727022/100722378-d843ee00-33c0-11eb-9c57-a8597c4c1a58.png)
![MQTTPacket_send_connect](https://user-images.githubusercontent.com/35727022/100722387-db3ede80-33c0-11eb-912d-6f4f53802add.png)
![MQTTVersion_0_(2)](https://user-images.githubusercontent.com/35727022/100722384-da0db180-33c0-11eb-8654-bbb0caebe441.png)

** Environment (please complete the following information):**
 - OS: Platform specific, but using the linux code of the library
 - Version 1.3.6 and OpenSSL 1.1.1g

**Additional context**
Destroying the client and creating a new one will solve the problem but then the automatic reconnect can't be trusted for long periods without connection.
This is a fragment of the log where you can see MQTTPacket_send_connect failing (because of the MQTTVersion being 0)
![image](https://user-images.githubusercontent.com/35727022/100723687-6076c300-33c2-11eb-8423-1d57627579a5.png)

This one is the same system but at the first connection (succeeding)
![image](https://user-images.githubusercontent.com/35727022/100724118-d24f0c80-33c2-11eb-83f1-566c06fd2fba.png)

**Comment by icraggs** [comment]
- OS Linux?  I thought the IDE looked like Windows.   You cut off the part of the trace which has the OpenSSL platform details.
- Static or dynamic linking? 
- Are you using another layer on top - like the C++ client?  
- If you can you could try version 1.3.7 to see if it makes any difference, although I realize the test takes a long time.

**Comment by alex-gimenez** [comment]
The IDE is Windows, but it's connecting to a vxworks system which is running the application.
The library was built statically and I'm using my own application on top (which is the interface between the machine's user and paho static library). This application just receives connection parameters to populate paho variables and creates a thread which will run as an infinite loop. This thread is using MQTTAsync functions.

For this case, I just call once MQTTAsync_connect and wait. Then the callback functions are called when they should (logs, connection failure, and so on).
I can try with 1.3.7 and post the results, but it would be nice to know if this is a problem originated in this platform or can also be reproduced in a more general OS (linux). Unfortunately, it's not possible for me to do those tests on a Linux machine.

**Comment by alex-gimenez** [comment]
I've run tests with version 1.3.7 but the problem is still there. The behaviour I observed is the same (MQTTVersion becomes 0 somewhere and forces MQTTPacket_send_connect to fail )

![MQTTVersion_0_v137](https://user-images.githubusercontent.com/35727022/100981959-c5a7f100-3547-11eb-9273-dd08c70aabc8.png)

The only change I observed is that "onConnectFailure" callback was being called in version 1.3.6 and now is "connectionlost", which I think makes more sense. That change seems related to https://github.com/eclipse/paho.mqtt.c/issues/974

**Comment by alex-gimenez** [comment]
I did a PR that has fixed the issue for me. I'm not sure if there could be other situations where something similar is still happening, but I can't reproduce it anymore.
https://github.com/eclipse/paho.mqtt.c/pull/1012

**Comment by icraggs** [comment]
Are you using the serverURIs field in your connect?  If so, with how many entries?

**Comment by alex-gimenez** [comment]
I'm just using MQTTAsync_createWithOptions giving a string with the hostname + port.
"ssl://test.mosquitto.org:8883"

**Comment by icraggs** [comment]
Thanks.  It's the "after a long period disconnected" that I don't understand.  I'd like to know what the cause is so that there aren't any unexpected side effects of a fix.

**Comment by icraggs** [comment]
I just had a thought which is if you set the MQTTVersion field in the connect options to MQTTVERSION_3_1_1 rather than MQTTVERSION_DEFAULT, this could distinguish between a memory overwrite (it still gets set to 0) and the field being wrongly initialized or not at all.

Also, as you have statically linked the library, this means that the memory is writeable by your application as well as the library, doesn't it? 

Other checks would be, does the same issue occur if:

a) the application is pointed at a non-existent address, so fails to connect from the start 
b) the broker being connected to is taken down, rather than the network cable being unplugged

I'm going to see if I can reproduce but if it's particular to your environment for some reason, then that wouldn't work.  When I say try to reproduce, I mean by leaving "for a long time" - I tried several shorter periods already and didn't see the problem.  But "a long time" is obviously not specific.

**Comment by icraggs** [comment]
I tried an overnight test on my Ubuntu system using the sample paho-c-sub, stopping a local broker then restarting it in the morning and the reconnect worked.

**Comment by jumoog** [comment]
Maybe its a DNS Problem?

**Comment by icraggs** [comment]
My thoughts are:

1. Due to environment - VxWorks?
2. Static linking allows application to overwrite memory?
3. Exactly specific combination of parameters?

I used the paho_c_sub sample to ssl://test.mosquitto.org:8883 overnight, disconnecting the network, and it reconnected ok in the morning.

I'm tempted to put the log message to catch this potential situation into 1.3.9 (see the PR) and then see if anyone else experiences it in practice.

**Comment by fpagliughi** [comment]
I've had some reports of this with the Rust client wrapper, running on Embedded Linux, but have not been able to reproduce it myself yet.

**Comment by icraggs** [comment]
I've put a change in which includes a trace message which should be written if occurs.  Might help to diagnose.

**Comment by alex-gimenez** [comment]
I'm sorry I couldn't reply sooner. I don't have access to those devices anymore so I won't be able to do more tests but I'll try to answer your questions:

1. Due to environment - VxWorks? I didn't try reproducing it in any other system so maybe... but we don't know

2. Static linking allows application to overwrite memory? This shouldn't happen, although it's technically possible doing it. However, this could eventually also produce a system crash, since it will be due to programming errors.

3. Exactly specific combination of parameters? The client was using reconnect, keep alive every 30s, tcp ssl connection, clean session. I can't remember all the other parameters, sorry.

Maybe with that trace message other people will also report it, thanks for your work

**Comment by linxingyang** [comment]
Hi.
Seems i met the similar problem.
* env
    * linux arm, rk3308, embeddded system.
    * IOT device has two netcards:  cable and 4G,  default using cable, and if cable is unavailable( plug off ) , switch to 4G, once cable is available again, switch to cable.
    * paho.mqtt.c 1.3.8, using Async APIs.
    * mosquitto 2.0.11

Test: both cable and 4G are available first,  mqtt connected by cable, then plug off cable, waiting for mqtt connected by 4G, then plug in cable, waiting for mqtt connected by cable again ...... after do that few times(sometimes longer),  the mqtt is block.  i found
* the connect callback is not triggered.
* and when block, it always using MQTT3 protocol (using the default one, when MQTT4 connect fail, will fallback to mqtt3) 

so, i set only using mqtt4, and that problem disappear.
```
mqttConnOpts.MQTTVersion = MQTTVERSION_3_1_1;
```
The mqtt server is mosquitto 2.0.11, and using mosquitto_pub/sub with MQTT3 to test the server, it's work fine with MQTT3.

And now, The same problem happened again when only using mqtt4, i guess/suspect that because frequently connect and disconnect with netcard switched, leding the connect callback not triggered.

---
I'm trying to figure out the scence and what happened now.
I find this issue under paho.mqtt.c 1.3.9 milestone, so i will base on the newest version to do the same test.

**Comment by yxjeag** [comment]
> Hi. Seems i met the similar problem.
> 
> * env
>   
>   * linux arm, rk3308, embeddded system.
>   * IOT device has two netcards:  cable and 4G,  default using cable, and if cable is unavailable( plug off ) , switch to 4G, once cable is available again, switch to cable.
>   * paho.mqtt.c 1.3.8, using Async APIs.
>   * mosquitto 2.0.11
> 
> Test: both cable and 4G are available first, mqtt connected by cable, then plug off cable, waiting for mqtt connected by 4G, then plug in cable, waiting for mqtt connected by cable again ...... after do that few times(sometimes longer), the mqtt is block. i found
> 
> * the connect callback is not triggered.
> * and when block, it always using MQTT3 protocol (using the default one, when MQTT4 connect fail, will fallback to mqtt3)
> 
> so, i set only using mqtt4, and that problem disappear.
> 
> ```
> mqttConnOpts.MQTTVersion = MQTTVERSION_3_1_1;
> ```
> 
> The mqtt server is mosquitto 2.0.11, and using mosquitto_pub/sub with MQTT3 to test the server, it's work fine with MQTT3.
> 
> And now, The same problem happened again when only using mqtt4, i guess/suspect that because frequently connect and disconnect with netcard switched, leding the connect callback not triggered.
> 
> I'm trying to figure out the scence and what happened now. I find this issue under paho.mqtt.c 1.3.9 milestone, so i will base on the newest version to do the same test.

I met this issue in same scene, I would like to ask that how do you slove it?
