### ISSUE TITLE
Whenever topic is receiving memory there is some amount of memory leak

### ISSUE THREAD

**Issue by cvmohan68** [eclipse-paho/paho.mqtt.c#1123]
Whenever some message received to client on subscribed topic, there is some amount of memory leak. I have create pull request 
https://github.com/eclipse/paho.mqtt.c/pull/1120
But unfortunately there is an issue in pull request ( I am new to this environment) can any one resolve the issue and see the code changes and post the comments.

**Comment by icraggs** [comment]
You have to free the topic name in the message arrived callback using the MQTTClient_free function as well as freeing the message with MQTTClient_freeMessage.  See the paho_cs_sub.c sample for an example.

This is because the application might store or otherwise manipulate the message and topic and only free them at some later point, so we avoid having to reallocate the memory.

**Comment by icraggs** [comment]
I assume that's answered this issue.

**Comment by cvmohan68** [comment]
Yes it addressed and I am able to fix it, Thanks for support
