### ISSUE TITLE
Possible subscribe wildcards bug

### ISSUE THREAD

**Issue by ingamedeo** [eclipse-paho/paho.mqtt.c#143]
When subscribing to:

> /test/hello/send/+/

Messages sent to **/test/hello/** are received. 

I believe that /test/hello/send/+ should receive only messages from topics like

> /test/hello/send/TEST1
> /test/hello/send/TEST2
> etc...

Am I wrong?

Cheers,
Amedeo

**Comment by ralight** [comment]
This is much more likely to be a broker bug than a client bug I'd say.

You can test it by running a local instance of mosquitto "mosquitto -p <port> -v" and then connecting to it with your client. You'd expect to see a log line like:

> 1465637757: Received SUBSCRIBE from clientid
> 1465637757:     /test/hello/send/+/ (QoS 0)

This shows you what the broker receives.

Another possibility is that you subscribed with clean session set to 0 in an earlier session where you subscribed to /test/hello/

A final point - your understanding of the subscriptions isn't quite right. A subscription to `/test/hello/send/+/` will not match for a topic of `/test/hello/send/TEST1` because the final `/` isn't present.

**Comment by ingamedeo** [comment]
Thanks a lot,

You have been really helpful. I solved my issue: the clean session flag was
set to 0.

Best regards,
Amedeo

**Comment by ralight** [comment]
Good to hear, I'll close this issue then.
