### ISSUE TITLE
const eyecatchers creates non-copyable structs in C++

### ISSUE THREAD

**Issue by fpagliughi** [eclipse-paho/paho.mqtt.c#168]
Some of the structures in the C library use a variable "eyecatcher" array, such as MQTTAsync_message:

typedef struct
{
    /*\* The eyecatcher for this structure.  must be MQTM. */
    char struct_id[4];
...
} MQTTAsync_message;

But some of the other struct's make the array constant, like MQTTAsync_willOptions:

typedef struct
{
    /*\* The eyecatcher for this structure.  must be MQTW. */
    const char struct_id[4];
...
} MQTTAsync_willOptions;

The const within the structure makes the whole structure non-copyable.

**Comment by guilhermeferreira** [comment]
According to the C++ standard "a defaulted copy/move assignment operator for class X is defined as deleted if X has a non-static data member of const non-class type". In other words, the compiler does not provide a copy assignment operator for structs and classes that have const data members. Because you can't assign a value to a const. The compiler probably issue a error like "attempting to reference a deleted function". And the deleted function being `operator=(const X&)`. 

But if we remove the const qualifier from the `struct_id`, we have a non-const `struct_id` array pointing to a constant char literal `{'M', 'Q', 'T', 'W'}`.

```
typedef struct
{
	char struct_id[4];
	/* ... */
} MQTTAsync_willOptions;

#define MQTTAsync_willOptions_initializer { {'M', 'Q', 'T', 'W'}, /* ... */ }
```

The other options I can think are infeasible. Like make `struct_id` a static member or a pointer. Or they break language rules, or they break the code.

**Comment by icraggs** [comment]
So we should remove the const from all these eyecatchers?  Is everyone agreed on that?

**Comment by fpagliughi** [comment]
It doesn't add a lot of protection in C, since you can bypass it with a memcpy to the address of the struct, and it makes using the stuct more difficult. Yes, let's remove them!

**Comment by icraggs** [comment]
Change added to the develop branch.  Thanks.

**Comment by fpagliughi** [comment]
Great! Thanks.
