### ISSUE TITLE
Paho C client does not support SNI extension of TLS

### ISSUE THREAD

**Issue by miketran78727** [eclipse-paho/paho.mqtt.c#171]
Similar to Python's issue eclipse/paho.mqtt.python#11, we need to provide the support in the C client.

**Comment by icraggs** [comment]
1) are you sure we don't support it, and 
2) what do we need to do to do so?

A quick perusal of some archives indicates OpenSSL support went in in 0.9.8.

**Comment by ralight** [comment]
The relevant function is `SSL_set_tlsext_host_name()`.

**Comment by icraggs** [comment]
Thanks Roger, finding that information in the OpenSSL doc, or elsewhere, doesn't seem to be straightforward.

**Comment by icraggs** [comment]
Is it ok for this capability to be turned on all the time, or does it need to have an option to turn it off?

**Comment by miketran78727** [comment]
Yes, It is OK for SNI to be turned on all the time.  According to http://www.ietf.org/rfc/rfc4366.txt 
````
-  Clients typically request the use of extensions via the extended
      client hello message described in Section 2.1. TLS requires
      servers to accept extended client hello messages, even if the
      server does not "understand" the extension.
````

**Comment by icraggs** [comment]
Thanks Mike. That's good.  I've added a proposed fix to the develop branch.  The regression tests work, but I've not had chance to try the SNI function out yet.  If anyone wants to try, please do, and let me know what you find.  Thanks.

**Comment by miketran78727** [comment]
Ian, Thanks.  I am currently busy with other work right now.  I will find some time early next month to try the SNI function and then close this issue.

**Comment by Alleyfield** [comment]
Did you get around testing the SNI function @miketran78727 as this issues is still open?
We're establishing a connection with develop branch build Paho but not getting connected. Thus we have the entire setup readily available.

With level of trace set to PROTOCOL we get the following log output
140737324693248:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:s3_pkt.c:1487:SSL alert number 48
20170306 143120.340 received 0 256 buflen 5
20170306 143120.340 received 771 21 buflen 2
**20170306 143120.340 SSL alert read:fatal:unknown CA**

And now we're looking into how to output that certificate in order to validate what certificate is being returned.

**Comment by miketran78727** [comment]
@Alleyfield Per our conversation on _**slack**_, you are now seeing correct certificate from Watson IoT Platform.  Thanks for testing.

**Comment by Alleyfield** [comment]
Yes, with wireshark traffic logs it can be seen SNI information is being sent out during "Client Hello" and we receive the uploaded certs. There is something else going on in the cert chain with IoTP.
Thank you

**Comment by icraggs** [comment]
This is now in develop and master branches.  Confirmed reports of it working.
