### ISSUE TITLE
cross-compilation error

### ISSUE THREAD

**Issue by BeLearner** [eclipse-paho/paho.mqtt.c#207]
When I type comand:

*cmake -GNinja -DPAHO_BUILD_SAMPLES=TRUE -DCMAKE_TOOLCHAIN_FILE=~/git/org.eclipse.paho.mqtt.c/cmake/toolchain.win64.cmake ~/git/org.eclipse.paho.mqtt.c*

and then:

*ninja*

when it builts samples,I get error "windows.h not found".Then I delete *"-DPAHO_BUILD_SAMPLES=TRUE"* and try:

cmake -GNinja -*DCMAKE_TOOLCHAIN_FILE=~/git/org.eclipse.paho.mqtt.c/cmake/toolchain.win64.cmake ~/git/org.eclipse.paho.mqtt.c*

It works.So please modify this instruction in README.

**Comment by andnig** [comment]
Since version 1.2.1, this problem is not avoided by simply deleting "-DPAHO_BUILD_SAMPLES=TRUE". 
As it seems, this cross-compilation error is due to case-sensitivity of some include-statements (#include windows.h vs. #include Windows.h). There are as far as I know 3 other includes which are sometimes upper case and sometimes lower case in the source files.
This is not a problem on either Windows or Linux builds however gets a problem, when compiling for windows on linux.
In general, changing all includes to lower case would be appropriate and correct, what do you think? 
Unfortunately, I don't have the resources at the moment to address this issue, however maybe my input may help to resolve this issue.

**Comment by icraggs** [comment]
There are two files recently introduced which refer to Windows.h rather than windows.h.  The samples refer to windows.h - but it seems that they are causing an issue?  It's easy to change all references to lower case if that will help.

I always use a Windows machine for building Windows applications, and I don't meet an issue.

**Comment by icraggs** [comment]
All references to Windows.h are now windows.h.
