### ISSUE TITLE
The return value of connect in the function Socket_new in Socket.c is SOCKET_ERROR, but the specfic error is WSA_INVALID_HANDLE.

### ISSUE THREAD

**Issue by guobaoteacher** [eclipse-paho/paho.mqtt.c#243]
Hi, all,
  I have a problem when I use the souce of mqtt. I use it in synchronous way. But it fails when I use MQTTClient_connect to connect the server. I find the return value of connect in the function Socket_new in Socket.c is SOCKET_ERROR, but the specfic error is WSA_INVALID_HANDLE, i don't know why. But it runs successfully when I annotation 'rc = ioctl(sock, FIONBIO, &flag); ' in the function ocket_setnonblocking in Socket.c. Thank you for your attention.

**Comment by icraggs** [comment]
It is that way so that the code using it in the client can be the same regardless of whether the operating system is Windows, Linux or MacOS.  Normalizing the error codes allows this.

**Comment by AdrianMoranMontes** [comment]
I experienced this same workmode in a Windows compilation. Same as guobaoteacher, I concluded that commenting ioctl call it works fine. The issue is nopt with the ioctl call, is with WSAGetLastError.

Somehow, FUNC_ENTY and FUNC_EXIT_RC macros employed in Socket_error function invalidates de error returned by WSAGetLastError. Probably, those macros generate new error that overrides MQTT socket error (I have to research about this).

Test code:
```
int Socket_error(char* aString, int sock)
{
#if defined(WIN32) || defined(WIN64)
        int errno;
        printf("CONNECT 1: %d\n", WSAGetLastError());
#endif

        //FUNC_ENTRY;
#if defined(WIN32) || defined(WIN64)
        printf("CONNECT 2: %d\n", WSAGetLastError());
        errno = WSAGetLastError();
        printf("CONNECT 3: %d\n", WSAGetLastError());
#endif
        if (errno != EINTR && errno != EAGAIN && errno != EINPROGRESS && errno != EWOULDBLOCK)
        {
                if (strcmp(aString, "shutdown") != 0 || (errno != ENOTCONN && errno != ECONNRESET))
                        Log(TRACE_MINIMUM, -1, "Socket error %s(%d) in %s for socket %d", strerror(errno), errno, aString, sock);
        }
        //FUNC_EXIT_RC(errno);
        return errno;
}
```

Output:
```
[ RUN      ] CTestPahoCs.SimpleSuccessOperation
CONNECT 1: 10035
CONNECT 2: 10035
CONNECT 3: 10035
[       OK ] CTestPahoCs.SimpleSuccessOperation (138 ms)
```


Output with FUNC_ENTRY macro:
```
[ RUN      ] CTestPahoCs.SimpleSuccessOperation
CONNECT 1: 10035
CONNECT 2: 6
CONNECT 3: 6
CONNECT 1: 10035
CONNECT 2: 6
CONNECT 3: 6
../../../../Caesar/Protocols/Paho/Test/test_paho_cs.cpp(300): error: Expected equality of these values:
  0
  this->connect_client()
    Which is: '\xFF' (-1)
[  FAILED  ] CTestPahoCs.SimpleSuccessOperation (43 ms)
```

I will try yo fix this, but it seems like some other thread is overwritting the WSAGetLastError code while FUNC_ENTRY macro is blocked on for mutex.

**Comment by AdrianMoranMontes** [comment]
The issue is related with the use of static library, which in Windows does not initializes some resources (mutexes). FUNC_ENTRY tries to lock an  unitialized mutex, which fails and change de last error returned by WSAGetLastError.

Related issues: #263 #341.
