### ISSUE TITLE
Possible inifinite loop in MQTTClient.c (MQTTClient_publish)?

### ISSUE THREAD

**Issue by sayegh** [eclipse-paho/paho.mqtt.c#277]
We experienced MQTTClient_publish didn't return sometimes, and it appeared it had something to do with high load. I don't have an in-depth understanding of the code, but I've found this loop in MQTTClient_publish:

```
	/* If outbound queue is full, block until it is not */
	while (m->c->outboundMsgs->count >= m->c->maxInflightMessages || 
Socket_noPendingWrites(m->c->net.socket) == 0) /* wait until the socket is free of large packets being written */
```

Assuming the loop should wait until the socket is clear (as the comment states), shouldn't it be an AND (&&) condition? 

In other words: Stay in the loop IF the buffer is full AND the socket is NOT clear? Because the buffer is and stays full, so the condition remains true forever.

Thanks for any help.

**Comment by icraggs** [comment]
I believe what the loop does is correct.

Socket_noPendingWrites() returns 1 if there are no outstanding writes to the socket, at which point the second clause will be false, and the loop will terminate.

There's a second loop where the publish is waiting tor the packet to be written to the socket, so it could also be held up there.

It's possible that taking a client trace could shed some light on the situation, but only if you could catch the time when it happens (set MQTT_C_CLIENT_TRACE=ON or filename)

**Comment by sayegh** [comment]
Thanks for your reply. Actually, the second clause may be false, but the first part is still true, so in total an OR makes it true - should this probably be an AND?

**Comment by icraggs** [comment]
The loop should continue to run if either condition is true, unless possibly it is QoS 0, but I thought it was better to hold off in that case too.   If the inflight message queue is full, it means the client is waiting for a response from the server to a QoS 1 or 2 message.  If there are pending writes for the socket, it means that we can't write to the socket.

Setting the "reliable" flag to false in the connect options allows up to 10 messages to be inflight at any one time (the default is 1).  (I think the name "reliable" was a bit pessimistic).  This should only be used with cleansession=false, as if the TCP connection is broken, the inflight message state will be thrown away if cleansession=true.

**Comment by hubslave** [comment]
Sorry to bring up a closed issue, but I've encountered a similar issue, and @sayegh: are you calling MQTTClient_publish from inside a messageArrived callback? Because if you hit the max in-flight publications limit there, the client will deadlock: MQTTClient_publish will block waiting for space to free up in the max in-flight message queue, but because the blocking happens inside the client's event loop, it can't free the space.

**Comment by hubslave** [comment]
Sorry to revive this old issue, but I encountered a similar problem, and @sayegh: are you calling MQTTClient_publish from inside a messageArrived callback? Because if the inflight message queue is full, that's a deadlock: MQTTClient_publish will wait for space in the queue to free up, but the MQTTClient message loop can't do it, because it's blocked in MQTTClient_publish.

**Comment by sayegh** [comment]
@hubslave 
Actually we're doing exactly that, because the incoming message triggers a "reply", which is IMHO a very typical use case.

However, we've made our suggested change (AND instead of OR) mentioned above, and everything works just fine.

Rationale see above.

Rationale towards @icraggs follow-up:
If "Socket_noPendingWrites() returns 1" implies that the other condition is also false (needed to terminate the loop), why have a second condition at all?

Anyway, I'm not pretending to actually understand the code to its full extent.
