### ISSUE TITLE
Calling MQTTAsync_connect after the "connection lost callback" doesn't reconnect the client

### ISSUE THREAD

**Issue by devzeb** [eclipse-paho/paho.mqtt.c#283]
I'm not using the auto reconnect feature.
This happens after restarting the broker. 

After the connection lost function get's called I'm trying to manually reconnect with MQTTAsync_connect. Most of the time the client doesn't reconnect to the broker. The reconnect only succeeds when I'm restarting the broker fast enough.

Trace: (https://github.com/eclipse/paho.mqtt.c/files/1033654/MQTTAsync_connect.reconnect.bug.txt)

I'm using version 1.1.0 on Windows.

**Comment by icraggs** [comment]
Do you try the connect more than once?  Does the connect fail as expected if the broker is not restarted quickly enough?  To state the obvious, the connect call may not work if the broker is not running at that point.

**Comment by devzeb** [comment]
No, i'm not trying to connect more than once. This is what i do:
1. "MQTTAsync_connectionLost" callback gets called as soon as i shut down the broker
2. I'm creating a new "MQTTAsync_connectOptions" instance and set the "onSuccess" & "onFailure" callback
3. I'm calling the "MQTTAsync_connect" function and wait
4. I'm neither getting the "onSuccess" nor the "onFailure" callback, except when i restart the broker instantly after i shut it down

Maybe there is something wrong with the "onFailure" callback?

**Comment by icraggs** [comment]
Taking a trace by setting the environment variable MQTT_C_CLIENT_TRACE=ON may give a better idea of what is happening.  It's possible that the TCP connect call is taking a long time because the broker receiving port is neither fully closed nor fully operational.  The library should time out and call the failure callback if the TCP connect does not work.

**Comment by GiveMeMoreMtDew** [comment]
I was also trying to reconnect by calling MQTTAsync_connect from the connectionLost callback.
The automaticReconnect parameter is set to 0.
A log file (with comments added by me) is attached for the following scenario:

A client application is running on the same Windows 10 PC as the Mosquitto broker.
The client application creates four separate objects (Client 1, Client 2, Client 3, 
and Client 4).  Each object is a separate MQTT client.

Broker is started.
Client application is started and all objects connect successfully.
Broker is terminated using CTRL-C.
Broker is restarted.
Some objects reconnect.  The Linked list appears to "lose" some of the
commands and/or sockets and not all of the objects reconnect.

C:\Projects\IRAD\PAHO\Win32\Debug>wizbang 4
=========================================================
                   Trace Output
Product name: Paho Asynchronous MQTT C Client Library
Version: 1.1.0
Build level: 4/21/2017
=========================================================
19691231 180000.000 the src string is truncated
19691231 180000.000 Connecting to serverURI localhost:1883 with MQTT version 4
19691231 180000.000 the src string is truncated
19691231 180000.000 New socket 404 for localhost, port 1883
19691231 180000.000 Connect pending
19691231 180000.000 the src string is truncated
19691231 180000.000 Connecting to serverURI localhost:1883 with MQTT version 4
19691231 180000.000 the src string is truncated
19691231 180000.000 New socket 420 for localhost, port 1883
19691231 180000.000 Connect pending
19691231 180000.000 the src string is truncated
19691231 180000.000 Connecting to serverURI localhost:1883 with MQTT version 4
19691231 180000.000 the src string is truncated
19691231 180000.000 New socket 424 for localhost, port 1883
19691231 180000.000 Connect pending
19691231 180000.000 Connecting to serverURI localhost:1883 with MQTT version 4
19691231 180000.000 the src string is truncated
19691231 180000.000 New socket 432 for localhost, port 1883
19691231 180000.000 Connect pending
20170713 132742.489 404 Client 1 -> CONNECT cleansession: 1 (0)
20170713 132742.489 420 Client 2 -> CONNECT cleansession: 1 (0)
20170713 132742.489 424 Client 3 -> CONNECT cleansession: 1 (0)
20170713 132742.489 432 Client 4 -> CONNECT cleansession: 1 (0)
20170713 132742.489 404 Client 1 <- CONNACK rc: 0
20170713 132742.489 0 responses removed for client Client 1
20170713 132742.489 0 commands removed for client Client 1
20170713 132742.489 Calling connect success for client Client 1

Client 1 has connected to localhost:1883

20170713 132742.489 420 Client 2 <- CONNACK rc: 0
20170713 132742.489 0 responses removed for client Client 2
20170713 132742.489 0 commands removed for client Client 2
20170713 132742.489 Calling connect success for client Client 2

Client 2 has connected to localhost:1883

20170713 132742.489 424 Client 3 <- CONNACK rc: 0
20170713 132742.489 0 responses removed for client Client 3
20170713 132742.489 0 commands removed for client Client 3
20170713 132742.489 Calling connect success for client Client 3

Client 3 has connected to localhost:1883

20170713 132742.489 432 Client 4 <- CONNACK rc: 0
20170713 132742.489 0 responses removed for client Client 4
20170713 132742.489 0 commands removed for client Client 4
20170713 132742.489 Calling connect success for client Client 4

Client 4 has connected to localhost:1883

*** Broker is terminated here ***

20170713 132745.196 Error from MQTTAsync_cycle() - removing socket 404
20170713 132745.196 404 Client 1 -> DISCONNECT (0)
20170713 132745.196 Removed socket 404
20170713 132745.196 0 responses removed for client Client 1
20170713 132745.196 0 commands removed for client Client 1
20170713 132745.196 Calling connectionLost for client Client 1

Client 1 has been disconnected because of a socket error.

20170713 132745.196 Connecting to serverURI localhost:1883 with MQTT version 4
20170713 132745.196 the src string is truncated
20170713 132745.196 New socket 404 for localhost, port 1883
20170713 132745.196 Connect pending
20170713 132745.196 Error from MQTTAsync_cycle() - removing socket 404
20170713 132745.196 Removed socket 404
20170713 132745.196 Error from MQTTAsync_cycle() - removing socket 420
20170713 132745.196 420 Client 2 -> DISCONNECT (0)
20170713 132745.196 Removed socket 420
20170713 132745.196 0 responses removed for client Client 2
20170713 132745.196 0 commands removed for client Client 2
20170713 132745.196 Calling connectionLost for client Client 2

Client 2 has been disconnected because of a socket error.

20170713 132745.196 Error from MQTTAsync_cycle() - removing socket 424
20170713 132745.196 Connecting to serverURI localhost:1883 with MQTT version 4
20170713 132745.223 the src string is truncated

Next line shows a new socket created and (assumed to be) assigned to Client 2.

20170713 132745.223 New socket 420 for localhost, port 1883
20170713 132745.223 Connect pending
20170713 132745.223 424 Client 3 -> DISCONNECT (0)
20170713 132745.223 Removed socket 424
20170713 132745.223 0 responses removed for client Client 3
20170713 132745.223 0 commands removed for client Client 3
20170713 132745.223 Calling connectionLost for client Client 3

Client 3 has been disconnected because of a socket error.

20170713 132745.223 Connecting to serverURI localhost:1883 with MQTT version 4
20170713 132745.223 the src string is truncated
20170713 132745.223 New socket 424 for localhost, port 1883
20170713 132745.223 Connect pending
20170713 132745.223 Error from MQTTAsync_cycle() - removing socket 432

BUG starts here (I think).  It appears that Client 2 attempted to send the CONNECT command 
over the new, but still diconnected, socket 420. 

20170713 132745.223 Socket error Unknown error(10057) in WSASend - putdatas for socket 420
20170713 132745.223 420 Client 2 -> CONNECT cleansession: 1 (-1)
20170713 132745.223 Removed socket 420

The following TRACE is printed in MQTTAsync_connecting just before a call to MQTTAsync_addCommand
which reinserts the CONNECT command into the linked list.

20170713 132745.223 Connect failed, more to try (3)
20170713 132745.223 Connecting to serverURI localhost:1883 with MQTT version 3
20170713 132745.223 the src string is truncated
20170713 132745.223 New socket 420 for localhost, port 1883

And 27 milliseconds later socket 420 fails a test in MQTTAsync_cycle and is removed
and never replaced.  Client 2 is disconnected and will not attempt any further 
reconnections.

20170713 132745.250 Connect pending
20170713 132745.250 Error from MQTTAsync_cycle() - removing socket 420
20170713 132745.250 Removed socket 420
20170713 132745.250 432 Client 4 -> DISCONNECT (0)
20170713 132745.250 Removed socket 432
20170713 132745.250 0 responses removed for client Client 4
20170713 132745.250 0 commands removed for client Client 4
20170713 132745.250 Calling connectionLost for client Client 4

Client 4 has been disconnected because of a socket error.

The following line indicates that Client 3 attempted to send the CONNECT command
using the new, but still disconnected, socket 424
 
20170713 132745.250 Socket error Unknown error(10057) in WSASend - putdatas for socket 424
20170713 132745.250 424 Client 3 -> CONNECT cleansession: 1 (-1)
20170713 132745.250 Removed socket 424
20170713 132745.250 Connect failed, more to try (3)
20170713 132745.250 Connecting to serverURI localhost:1883 with MQTT version 3
20170713 132745.250 the src string is truncated
20170713 132745.250 New socket 444 for localhost, port 1883
20170713 132745.250 Connect pending

hmmm! A socket to client map has failed.

20170713 132745.250 Could not find client corresponding to socket 424


20170713 132745.250 Connecting to serverURI localhost:1883 with MQTT version 4
20170713 132745.250 the src string is truncated
20170713 132745.250 New socket 424 for localhost, port 1883
20170713 132745.274 Connect pending
20170713 132745.274 Removed socket 444
20170713 132745.274 0 responses removed for client Client 3
20170713 132745.274 0 commands removed for client Client 3
20170713 132745.274 Calling connect failure for client Client 3

ERROR: Client 3 Connection failed: TCP connect timeout. Attempting to reconnect.

20170713 132745.274 Removed socket 424
20170713 132745.274 Connect failed with timeout, more to try
20170713 132745.274 Connecting to serverURI localhost:1883 with MQTT version 3
20170713 132745.274 the src string is truncated
20170713 132745.274 New socket 404 for localhost, port 1883
20170713 132745.274 Connect pending
20170713 132745.274 Connecting to serverURI localhost:1883 with MQTT version 4
20170713 132745.274 the src string is truncated
20170713 132745.274 New socket 444 for localhost, port 1883
20170713 132745.274 Connect pending
20170713 132745.274 404 Client 4 -> CONNECT cleansession: 1 (0)
20170713 132745.274 444 Client 3 -> CONNECT cleansession: 1 (0)
20170713 132745.274 404 Client 4 <- CONNACK rc: 0
20170713 132745.274 0 responses removed for client Client 4
20170713 132745.274 0 commands removed for client Client 4
20170713 132819.306 Calling connect success for client Client 4

Client 4 has connected to localhost:1883

20170713 132819.306 444 Client 3 <- CONNACK rc: 0
20170713 132819.306 0 responses removed for client Client 3
20170713 132819.306 0 commands removed for client Client 3
20170713 132819.306 Calling connect success for client Client 3

Client 3 has connected to localhost:1883

---> Clients 1 & 2 have been lost.  <---

20170713 132819.306 444 Client 3 -> PINGREQ (0)
20170713 132819.306 404 Client 4 -> PINGREQ (0)
20170713 132819.306 404 Client 4 <- PINGRESP
20170713 132819.306 444 Client 3 <- PINGRESP

Client application is terminated here

20170713 132819.306 0 responses removed for client Client 1
20170713 132819.306 0 commands removed for client Client 1
20170713 132819.306 Removed client Client 1 from bstate->clients, socket 0
20170713 132819.306 444 Client 3 -> DISCONNECT (0)
20170713 132819.306 Removed socket 444
20170713 132819.306 0 responses removed for client Client 3
20170713 132819.306 0 commands removed for client Client 3
20170713 132819.306 Calling disconnect complete for client Client 3
Client 3 has disconnected from the server.
20170713 132819.306 0 responses removed for client Client 2
20170713 132819.306 0 commands removed for client Client 2
20170713 132819.306 Removed client Client 2 from bstate->clients, socket 0
20170713 132849.790 404 Client 4 -> DISCONNECT (0)
20170713 132849.790 Removed socket 404
20170713 132849.790 0 responses removed for client Client 4
20170713 132849.790 0 commands removed for client Client 4
20170713 132849.790 Calling disconnect complete for client Client 4
Client 4 has disconnected from the server.
20170713 132849.790 0 responses removed for client Client 3
20170713 132849.790 0 commands removed for client Client 3
20170713 132849.790 Removed client Client 3 from bstate->clients, socket 0
20170713 132849.790 Could not find client corresponding to socket 444
20170713 132849.790 0 responses removed for client Client 4
20170713 132849.790 0 commands removed for client Client 4
20170713 132849.790 Removed client Client 4 from bstate->clients, socket 0
20170713 132849.790 Conn_count is 0
20170713 132849.790 sleeping
20170713 132849.790 Maximum heap use was 0 bytes

The results vary from run-to-run.
Sometimes all 4 objects reconnect.  Most of the time, only three objects reconnect.  
This is a rare example where only 2 objects reconnected.

Hope this helps.
Scott

**Comment by icraggs** [comment]
Which version of the code are you using?

**Comment by GiveMeMoreMtDew** [comment]
1.1.0
FYI, I compiled the PAHO DLL with Microsoft Visual Studio 2015.  The following preprocessor flags are defined:
NO_PERSISTENCE
NO_HEAP_TRACKING

**Comment by icraggs** [comment]
Please try 1.2.0.  There were some fixes in this area.

**Comment by GiveMeMoreMtDew** [comment]
1.2.0 fixed the problem.  

Thanks,
Scott

**Comment by icraggs** [comment]
Closing, as it's fixed in 1.2.

**Comment by rashed043** [comment]
Hello, first of all thank you for giving effort for developing the nice project. i am quite new in MQTT. Recently i started to develop the MQTT with vxwork. i am sucessfully deveped the publish protocol but could sucess with subscribe. it is always come to the function "MQTTClient_connectURIVersion"-> "MQTTClient_waitfor"-> if (running)-> if (*rc == 0 && packet_type != CONNECT && m->pack == NULL).
Actaully altime showing the pack is null and could not connect to the server. As i told, i am quite new so if i make confustion please consider that. my problem is, it is showing altime the packet is null. Could you please give any idea or suggestion why the packet is null

**Comment by rashed043** [comment]
sorry i could not sucess with MQTT subscribe and using Paho Mqtt c project.
