### ISSUE TITLE
Build both 32 and 64 bit Windows DLLs

### ISSUE THREAD

**Issue by rsaatpresys** [eclipse-paho/paho.mqtt.c#356]
I´m trying to build the sample paho_cs_sub.c using the Pre-built binaries for Windows.
I´m just creating a simple Visual studio 2015 Win32 console application using the file paho_cs_sub.c

I can build the executable using version 1.1.0

http://build.eclipse.org/technology/paho/C/1.1.0/

Using the version 1.2.0 I get LNK2019 unresolved external symbol error.

Example:
Error LNK2019 unresolved external symbol _MQTTClient_create referenced in function _main PahoTest T:\mqtt\pahotest\PahoTest\PahoTest\paho_cs_sub.obj 1

I noted, using dumbin program to export information from lib files, that version 1.1.0 has the underscore (_) before the function names and version 1.2.0 has no underscore.

Part of output of dumpbin program of version 1.1.0 (with underscore)

"Exports

ordinal name

_MQTTClient_connect
_MQTTClient_create"

Part of output of dumpbin program of version 1.2.0 (with no underscore)

"Exports

ordinal name

MQTTClient_connect
MQTTClient_create"

**Do you know if I need adjust some configuration in Visual Studio 2015 to use the lib files (ex: paho-mqtt3cs.lib) of the latest stable version of this mqtt library ?**

**Comment by icraggs** [comment]
Did you get the 1.2 binaries from https://projects.eclipse.org/projects/technology.paho/downloads?

**Comment by rsaatpresys** [comment]
Yes. I downloaded from the main paho mqtt page linking to the  page https://projects.eclipse.org/projects/technology.paho/downloads. 

I´m verifying the differences between lib versions typing  the command  below in Developer Command Prompt for Visual Studio 2015. 

dumpbin /all paho-mqtt3cs.lib

**Comment by fwinkelbauer** [comment]
I am having similar linker problems when trying to use the 1.2 binary in a Visual Studio 2005 project. The previous version 1.1 dlls works fine. I was able to build the projects `paho-mqtt3a` and `paho-mqtt3c` (which are the only two that I need) from [source](https://github.com/eclipse/paho.mqtt.c/archive/v1.2.0.zip) using Visual Studio 2017 after creating the `src/VersionInfo.h` file. The newly created dlls did not throw any linker errors.

**Comment by icraggs** [comment]
I've tried several ways to reproduce this error with new builds out of AppVeyor which I plan to update the download site with.  

Admittedly I've been using Visual Studio 2017 because that's the only one I have around now, but the AppVeyor builds are using 2013 and 2015.  You can go to the latest build on AppVeyor:

https://ci.appveyor.com/project/eclipsewebmaster/paho-mqtt-c/history

and the most recent ones now have a zip file with the build results under 'artifacts'.  Dumpbin shows the entry points with no leading underscores whichever way I build them.

**Comment by icraggs** [comment]
I've created 1.2.1 windows binaries with the new builds on AppVeyor.  They are now available from the Paho downloads web page.  I used them to build applications with the Visual Studio (latest version) command line on Windows 10.  On AppVeyor they are built with Visual Studio 2013.

I have encountered no problems with these binaries.

**Comment by mcolella** [comment]
Hello,
I tried everything and I'm not able to run newer library version.
I am using Visual C 2008 and I'am not able to link DLL function (I am using paho-mqtt3c) in both C and C++ projects due to missing prepend underscore on exported function names).
I also tried the 1.2.1 version but it is still missing underscores.
Last I tried to recompile the sources (https://github.com/eclipse/paho.mqtt.c/archive/v1.2.0.zip) but  here I was facing a compatibility problem since the project was created with a newer version of compiler and cannot be opened.
Since prepend underscore seems to be the standard for dll exported cdecl function (that is the standard C name decoration) could be possible to have the last dll version builded in this way as the previous  1.1.0 version was?
Otherwise, anyone knows a way to tell the compiler to not decorate external function name?

Regards

M. Colella

**Comment by mcolella** [comment]
Thanks for you answer.
I suspected that the dll could be 64 bit since in that environment, functions are not decorated. 
Unfortunately I'm dealing with a huge application that is the result of a porting from 16 to 32 bit; so to switch from 32 to 64 bit could be not immediate. Could be possible instead to have  in the future both 32 and 64 bit version of DLL?
Best Regards
M. Colella

**Comment by icraggs** [comment]
Ok.  I'll reopen this issue with an altered description for the next release.

**Comment by mcolella** [comment]
Thanks a lot.
I will wait for the 32 bit  1.2.0 version.
