### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by wijamw** [eclipse-paho/paho.mqtt.c#382]
I was trying to test the samples. I used gcc 7.2.0. But I always get the error about the code seems can't find the OsWrapper.h although it does exist because other lib that has same directory is working. So I decided to remove it for awhile. But I got new error saying that 

> /tmp/ccOx86NJ.o: In function `messageArrived':
paho_c_sub.c:(.text+0x5e2): undefined reference to `MQTTAsync_freeMessage'
paho_c_sub.c:(.text+0x5f0): undefined reference to `MQTTAsync_free'
/tmp/ccOx86NJ.o: In function `onConnect':
paho_c_sub.c:(.text+0x728): undefined reference to `MQTTAsync_subscribe'
/tmp/ccOx86NJ.o: In function `connectionLost':
paho_c_sub.c:(.text+0x791): undefined reference to `MQTTAsync_connect'
/tmp/ccOx86NJ.o: In function `main':
paho_c_sub.c:(.text+0x8f1): undefined reference to `MQTTAsync_create'
paho_c_sub.c:(.text+0x91c): undefined reference to `MQTTAsync_setCallbacks'
paho_c_sub.c:(.text+0x99e): undefined reference to `MQTTAsync_connect'
paho_c_sub.c:(.text+0xa2e): undefined reference to `MQTTAsync_disconnect'
paho_c_sub.c:(.text+0xa8b): undefined reference to `MQTTAsync_destroy'
collect2: error: ld returned 1 exit status <

Do I do something wrong and there is something happen?

**Comment by wijamw** [comment]
I used make then followed by sudo make install. Should I use cmake instead?

**Comment by icraggs** [comment]
I just tried the same sequence of commands on Ubuntu - they worked for me.  Is your OS expecting the libs to be installed in some other location than the Makefile default?

**Comment by icraggs** [comment]
Closing, in the absence of further information.

**Comment by saadmajid95** [comment]
I built using make but following code is not compiling with the following error.
`/*******************************************************************************
 * Copyright (c) 2012, 2018 IBM Corp.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v1.0 which accompany this distribution. 
 *
 * The Eclipse Public License is available at 
 *   http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at 
 *   http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *    Ian Craggs - initial contribution
 *******************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "MQTTAsync.h"

#if defined(_WRS_KERNEL)
#include <OsWrapper.h>
#endif

#define ADDRESS     "ssl://thingsxess.com:8883"
#define CLIENTID    "stark"
#define TOPIC       "test"
#define PAYLOAD     "Hello World!"
#define QOS         0
#define TIMEOUT     10000L

volatile MQTTAsync_token deliveredtoken;

int finished = 0;

void connlost(void *context, char *cause)
{
	MQTTAsync client = (MQTTAsync)context;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	int rc;

	printf("\nConnection lost\n");
	printf("     cause: %s\n", cause);

	printf("Reconnecting\n");
	conn_opts.keepAliveInterval = 20;
	conn_opts.cleansession = 1;
	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
 		finished = 1;
	}
}


void onDisconnect(void* context, MQTTAsync_successData* response)
{
	printf("Successful disconnection\n");
	finished = 1;
}


void onSend(void* context, MQTTAsync_successData* response)
{
	MQTTAsync client = (MQTTAsync)context;
	MQTTAsync_disconnectOptions opts = MQTTAsync_disconnectOptions_initializer;
	int rc;

	printf("Message with token value %d delivery confirmed\n", response->token);

	opts.onSuccess = onDisconnect;
	opts.context = client;

	if ((rc = MQTTAsync_disconnect(client, &opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start sendMessage, return code %d\n", rc);
		exit(EXIT_FAILURE);
	}
}


void onConnectFailure(void* context, MQTTAsync_failureData* response)
{
	printf("Connect failed, rc %d\n", response ? response->code : 0);
	finished = 1;
}


void onConnect(void* context, MQTTAsync_successData* response)
{
	printf("hello");
	MQTTAsync client = (MQTTAsync)context;
	MQTTAsync_responseOptions opts = MQTTAsync_responseOptions_initializer;
	MQTTAsync_message pubmsg = MQTTAsync_message_initializer;
	int rc;

	printf("Successful connection\n");
	
	opts.onSuccess = onSend;
	opts.context = client;

	pubmsg.payload = PAYLOAD;
	pubmsg.payloadlen = strlen(PAYLOAD);
	pubmsg.qos = QOS;
	pubmsg.retained = 0;
	deliveredtoken = 0;

	if ((rc = MQTTAsync_sendMessage(client, TOPIC, &pubmsg, &opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start sendMessage, return code %d\n", rc);
		exit(EXIT_FAILURE);
	}
}


int main(int argc, char* argv[])
{
	MQTTAsync client;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	int rc=5;
    int a;
	a= MQTTAsync_create(&client, ADDRESS, CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
	printf("a is %d",a);
	printf("Hey");
	MQTTAsync_setCallbacks(client, NULL, connlost, NULL, NULL);
    printf("check1\n");
	conn_opts.keepAliveInterval = 5;
	//conn_opts.username = "ssl://Ironman.azure-devices.net/stark";
	//conn_opts.password = "SharedAccessSignature sr=Ironman.azure-devices.net%2Fdevices%2Fstark&sig=eoAum3Hl2gWWiFVJT%2FhmUMwYH4NFAT%2B5fG8tRTm%2BbaA%3D&se=1558677763";
	conn_opts.cleansession = 1;
	printf("check2\n");
	conn_opts.onSuccess = onConnect;
    	//conn_opts.username = "Ironman/stark";
    	//conn_opts.password = "SharedAccessSignature sr=Ironman.azure-devices.net%2Fdevices%2Fstark&sig=eoAum3Hl2gWWiFVJT%2FhmUMwYH4NFAT%2B5fG8tRTm%2BbaA%3D&se=1558677763";
	printf("check3\n");
	conn_opts.onFailure = onConnectFailure;
	conn_opts.context = client;
	if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS)
	{
		printf("Failed to start connect, return code %d\n", rc);
		exit(EXIT_FAILURE);
	}
	else
	{
		printf("rc is %d ",rc);
	}

	printf("Waiting for publication of %s\n"
         "on topic %s for client with ClientID: %s\n",
         PAYLOAD, TOPIC, CLIENTID);
	while (!finished)
		#if defined(WIN32)
			Sleep(100);
		#else
			usleep(10000L);
		#endif

	MQTTAsync_destroy(&client);
 	return rc;
}

`


`/usr/bin/ld: /tmp/cccQ0wYz.o: in function `connlost':
MQTTAsync_publish.c:(.text+0x6c): undefined reference to `MQTTAsync_connect'
/usr/bin/ld: /tmp/cccQ0wYz.o: in function `onSend':
MQTTAsync_publish.c:(.text+0x178): undefined reference to `MQTTAsync_disconnect'
/usr/bin/ld: /tmp/cccQ0wYz.o: in function `onConnect':
MQTTAsync_publish.c:(.text+0x2c8): undefined reference to `MQTTAsync_sendMessage'
/usr/bin/ld: /tmp/cccQ0wYz.o: in function `main':
MQTTAsync_publish.c:(.text+0x36c): undefined reference to `MQTTAsync_create'
/usr/bin/ld: MQTTAsync_publish.c:(.text+0x3a0): undefined reference to `MQTTAsync_setCallbacks'
/usr/bin/ld: MQTTAsync_publish.c:(.text+0x3f4): undefined reference to `MQTTAsync_connect'
/usr/bin/ld: MQTTAsync_publish.c:(.text+0x460): undefined reference to `MQTTAsync_destroy'
collect2: error: ld returned 1 exit status`

**Comment by sergioaiello** [comment]
same issue
/usr/bin/ld: esp32PwrLogger.c:(.text+0x5fc): undefined reference to `MQTTClient_setCallbacks'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x618): undefined reference to `MQTTClient_connect'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x6a0): undefined reference to `MQTTClient_subscribe'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x6c0): undefined reference to `MQTTClient_subscribe'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x6e0): undefined reference to `MQTTClient_subscribe'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x718): undefined reference to `MQTTClient_connect'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x7d0): undefined reference to `MQTTClient_subscribe'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x7f0): undefined reference to `MQTTClient_subscribe'
/usr/bin/ld: esp32PwrLogger.c:(.text+0x810): undefined reference to `MQTTClient_subscribe'

**Comment by icraggs** [comment]
Make sure you're using the correct library, paho-mqtt3c for MQTTClient, paho-mqtt3a for MQTTAsync.

**Comment by sergioaiello** [comment]
first of all thank you. since I'm having trouble
The cmd I use is as follow and it worked fine before the release update (buster -> bullseye)
gcc -lpaho-mqtt3c -lpaho-mqtt3a -lpaho-mqtt3as -lpaho-mqtt3cs -o esp32PwrLogger esp32PwrLogger.c
I thought to solve by reinstalling the paho library and I followed the instructions:
- cd paho.mqtt.c      (former paho.mqtt.c dir)
- sudo make uninstall
- apt install build-essential gcc make cmake cmake-gui cmake-curses-gui
- apt install doxygen graphviz
- apt install libssl-dev
- git clone https://github.com/eclipse/paho.mqtt.c.git
- cd paho.mqtt.c  (latter  paho.mqtt.c  dir, just created by cloning)
- make (see below the output I got)
- sudo make install

`makemkdir -p build/output/samplesmkdir -p build/output/testecho OSTYPE is LinuxOSTYPE is Linuxmkdir -p buildsed -e "s/@CLIENT_VERSION@/1.3.11/g" -e "s/@BUILD_TIMESTAMP@/Wed 12 Oct 2022 06:25:07 PM CEST/g" src/[VersionInfo.h.in](http://versioninfo.h.in/) > build/VersionInfo.hcc -g -fPIC  -D_GNU_SOURCE -Os -Wall -fvisibility=hidden -Ibuild -DPAHO_MQTT_EXPORTS=1 -o build/output/libpaho-mqtt3c.so.1.3 src/Base64.c src/Clients.c src/Heap.c src/LinkedList.c src/Log.c src/Messages.c src/MQTTClient.c src/MQTTPacket.c src/MQTTPacketOut.c src/MQTTPersistence.c src/MQTTPersistenceDefault.c src/MQTTProperties.c src/MQTTProtocolClient.c src/MQTTProtocolOut.c src/MQTTReasonCodes.c src/MQTTTime.c src/OsWrapper.c src/Proxy.c src/SHA1.c src/SocketBuffer.c src/Socket.c src/StackTrace.c src/Thread.c src/Tree.c src/utf-8.c src/WebSocket.c  -shared -Wl,-init,MQTTClient_init -Wl,--start-group -pthread -lanl -Wl,--end-group -Wl,-soname,libpaho-mqtt3c.so.1ln -s libpaho-mqtt3c.so.1.3  build/output/libpaho-mqtt3c.so.1ln -s libpaho-mqtt3c.so.1 build/output/libpaho-mqtt3c.socc -g -fPIC  -D_GNU_SOURCE -Os -Wall -fvisibility=hidden -Ibuild -DPAHO_MQTT_EXPORTS=1 -o build/output/libpaho-mqtt3cs.so.1.3 src/Base64.c src/Clients.c src/Heap.c src/LinkedList.c src/Log.c src/Messages.c src/MQTTClient.c src/MQTTPacket.c src/MQTTPacketOut.c src/MQTTPersistence.c src/MQTTPersistenceDefault.c src/MQTTProperties.c src/MQTTProtocolClient.c src/MQTTProtocolOut.c src/MQTTReasonCodes.c src/MQTTTime.c src/OsWrapper.c src/Proxy.c src/SHA1.c src/SocketBuffer.c src/Socket.c src/SSLSocket.c src/StackTrace.c src/Thread.c src/Tree.c src/utf-8.c src/WebSocket.c -DOPENSSL  -shared -Wl,--start-group -pthread -lanl -ldl -lssl -lcrypto -Wl,--end-group -Wl,-init,MQTTClient_init -Wl,-soname,libpaho-mqtt3cs.so.1 -Wl,-no-whole-archiveln -s libpaho-mqtt3cs.so.1.3  build/output/libpaho-mqtt3cs.so.1ln -s libpaho-mqtt3cs.so.1 build/output/libpaho-mqtt3cs.socc -g -fPIC  -D_GNU_SOURCE -Os -Wall -fvisibility=hidden -Ibuild -DPAHO_MQTT_EXPORTS=1 -o build/output/libpaho-mqtt3a.so.1.3 src/Base64.c src/Clients.c src/Heap.c src/LinkedList.c src/Log.c src/Messages.c src/MQTTAsync.c src/MQTTAsyncUtils.c src/MQTTPacket.c src/MQTTPacketOut.c src/MQTTPersistence.c src/MQTTPersistenceDefault.c src/MQTTProperties.c src/MQTTProtocolClient.c src/MQTTProtocolOut.c src/MQTTReasonCodes.c src/MQTTTime.c src/OsWrapper.c src/Proxy.c src/SHA1.c src/SocketBuffer.c src/Socket.c src/StackTrace.c src/Thread.c src/Tree.c src/utf-8.c src/WebSocket.c  -shared -Wl,-init,MQTTAsync_init -Wl,--start-group -pthread -lanl -Wl,--end-group -Wl,-soname,libpaho-mqtt3a.so.1ln -s libpaho-mqtt3a.so.1.3  build/output/libpaho-mqtt3a.so.1ln -s libpaho-mqtt3a.so.1 build/output/libpaho-mqtt3a.socc -g -fPIC  -D_GNU_SOURCE -Os -Wall -fvisibility=hidden -Ibuild -DPAHO_MQTT_EXPORTS=1 -o build/output/libpaho-mqtt3as.so.1.3 src/Base64.c src/Clients.c src/Heap.c src/LinkedList.c src/Log.c src/Messages.c src/MQTTAsync.c src/MQTTAsyncUtils.c src/MQTTPacket.c src/MQTTPacketOut.c src/MQTTPersistence.c src/MQTTPersistenceDefault.c src/MQTTProperties.c src/MQTTProtocolClient.c src/MQTTProtocolOut.c src/MQTTReasonCodes.c src/MQTTTime.c src/OsWrapper.c src/Proxy.c src/SHA1.c src/SocketBuffer.c src/Socket.c src/SSLSocket.c src/StackTrace.c src/Thread.c src/Tree.c src/utf-8.c src/WebSocket.c -DOPENSSL  -shared -Wl,--start-group -pthread -lanl -ldl -lssl -lcrypto -Wl,--end-group -Wl,-init,MQTTAsync_init -Wl,-soname,libpaho-mqtt3as.so.1 -Wl,-no-whole-archiveln -s libpaho-mqtt3as.so.1.3  build/output/libpaho-mqtt3as.so.1ln -s libpaho-mqtt3as.so.1 build/output/libpaho-mqtt3as.socc  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/output -o build/output/paho_c_version -lpaho-mqtt3a src/MQTTVersion.c -ldlcc -o build/output/samples/MQTTClient_publish src/samples/MQTTClient_publish.c -lpaho-mqtt3cs  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/outputcc -o build/output/samples/MQTTClient_publish_async src/samples/MQTTClient_publish_async.c -lpaho-mqtt3cs  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/outputcc -o build/output/samples/MQTTClient_subscribe src/samples/MQTTClient_subscribe.c -lpaho-mqtt3cs  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/outputcc -o build/output/samples/paho_cs_pub src/samples/paho_cs_pub.c -lpaho-mqtt3cs  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/output src/samples/pubsub_opts.ccc -o build/output/samples/paho_cs_sub src/samples/paho_cs_sub.c -lpaho-mqtt3cs  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/output src/samples/pubsub_opts.ccc -o build/output/samples/MQTTAsync_subscribe src/samples/MQTTAsync_subscribe.c -lpaho-mqtt3as  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/outputcc -o build/output/samples/MQTTAsync_publish src/samples/MQTTAsync_publish.c -lpaho-mqtt3as  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/outputcc -o build/output/samples/paho_c_pub src/samples/paho_c_pub.c -lpaho-mqtt3as  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/output src/samples/pubsub_opts.ccc -o build/output/samples/paho_c_sub src/samples/paho_c_sub.c -lpaho-mqtt3as  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/output src/samples/pubsub_opts.ccc -DNOSTACKTRACE -DNOLOG_MESSAGES src/Thread.c -g -o build/output/test/test1 src/../test/test1.c -lpaho-mqtt3c  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -DNOSTACKTRACE -DNOLOG_MESSAGES src/Thread.c -g -o build/output/test/test15 src/../test/test15.c -lpaho-mqtt3c  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -DNOSTACKTRACE -DNOLOG_MESSAGES src/Thread.c -g -o build/output/test/test2 src/../test/test2.c -lpaho-mqtt3c  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -DNOSTACKTRACE -DNOLOG_MESSAGES src/Thread.c -g -o build/output/test/sync_client_test src/../test/sync_client_test.c -lpaho-mqtt3c  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -DNOSTACKTRACE -DNOLOG_MESSAGES src/Thread.c -g -o build/output/test/test_mqtt4sync src/../test/test_mqtt4sync.c -lpaho-mqtt3c  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -DNOSTACKTRACE -DNOLOG_MESSAGES src/Thread.c -g -o build/output/test/test10 src/../test/test10.c -lpaho-mqtt3c  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test3 src/../test/test3.c -lpaho-mqtt3cs  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/outputcc -g -o build/output/test/test4 src/../test/test4.c -lpaho-mqtt3a  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test45 src/../test/test45.c -lpaho-mqtt3a  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test6 src/../test/test6.c -lpaho-mqtt3a  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test9 src/../test/test9.c -lpaho-mqtt3a  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test95 src/../test/test95.c -lpaho-mqtt3a  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test_mqtt4async src/../test/test_mqtt4async.c -lpaho-mqtt3a  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test11 src/../test/test11.c -lpaho-mqtt3a  -I src -Wl,--start-group -pthread -lanl -Wl,--end-group -L build/outputcc -g -o build/output/test/test5 src/../test/test5.c -lpaho-mqtt3as  -I src -Wl,--start-group -pthread -lanl -lssl -lcrypto -Wl,--end-group -L build/output`

`sudo make install
mkdir -p build/output/samples
mkdir -p build/output/test
echo OSTYPE is Linux
OSTYPE is Linux
mkdir -p /usr/local/include
install -m 644  build/output/libpaho-mqtt3c.so.1.3 /usr/local/lib
install -m 644  build/output/libpaho-mqtt3cs.so.1.3 /usr/local/lib
install -m 644  build/output/libpaho-mqtt3a.so.1.3 /usr/local/lib
install -m 644  build/output/libpaho-mqtt3as.so.1.3 /usr/local/lib
install  build/output/paho_c_version /usr/local/bin
install  build/output/samples/paho_c_pub /usr/local/bin
install  build/output/samples/paho_c_sub /usr/local/bin
install  build/output/samples/paho_cs_pub /usr/local/bin
install  build/output/samples/paho_cs_sub /usr/local/bin
/sbin/ldconfig /usr/local/lib
ln -s libpaho-mqtt3c.so.1 /usr/local/lib/libpaho-mqtt3c.so
ln -s libpaho-mqtt3cs.so.1 /usr/local/lib/libpaho-mqtt3cs.so
ln -s libpaho-mqtt3a.so.1 /usr/local/lib/libpaho-mqtt3a.so
ln -s libpaho-mqtt3as.so.1 /usr/local/lib/libpaho-mqtt3as.so
install -m 644 src/MQTTAsync.h /usr/local/include
install -m 644 src/MQTTClient.h /usr/local/include
install -m 644 src/MQTTClientPersistence.h /usr/local/include
install -m 644 src/MQTTProperties.h /usr/local/include
install -m 644 src/MQTTReasonCodes.h /usr/local/include
install -m 644 src/MQTTSubscribeOpts.h /usr/local/include
install -m 644 src/MQTTExportDeclarations.h /usr/local/include
install -m 644 doc/man/man1/paho_c_pub.1 /usr/local/share/man/man1
install -m 644 doc/man/man1/paho_c_sub.1 /usr/local/share/man/man1
install -m 644 doc/man/man1/paho_cs_pub.1 /usr/local/share/man/man1
install -m 644 doc/man/man1/paho_cs_sub.1 /usr/local/share/man/man1
`

**Comment by icraggs** [comment]
So that looks like it worked?

In this command:

     gcc -lpaho-mqtt3c -lpaho-mqtt3a -lpaho-mqtt3as -lpaho-mqtt3cs -o esp32PwrLogger esp32PwrLogger.c

I never include more than one and certainly not both the cs/c and as/a libraries. Just pick the one you need (paho-mqtt3cs?) and try that.

**Comment by sergioaiello** [comment]
Thank you for the hint. I see paho-mqtt3cs alone works fine. I'm now working with a saved backup image (Buster). It is just a workaround so to continue other tasks. As soon as I have the chance, I'll repeat the apt update and see if I can replicate the problem.
Thank you by now!

**Comment by jasim-j** [comment]
im using visual studio code im getting problem like this



C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x7a): undefined reference to `MQTTAsync_connect'
C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x19f): undefined reference to `MQTTAsync_disconnect'
C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x275): undefined reference to `MQTTAsync_disconnect'
C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x3db): undefined reference to `MQTTAsync_sendMessage'
C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x478): undefined reference to `MQTTAsync_create'
C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x4cb): undefined reference to `MQTTAsync_setCallbacks'
C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x530): undefined reference to `MQTTAsync_connect'
C:\Users\MOHAMM~1\AppData\Local\Temp\ccWE3Haz.o:MQTTAsync_publish.c:(.text+0x5a1): undefined reference to `MQTTAsync_destroy'
