### ISSUE TITLE
connection lost event not firing with MQTTAsync

### ISSUE THREAD

**Issue by tropas2001** [eclipse-paho/paho.mqtt.c#407]
I'm struggling to get the connectionlost event to fire in the event of socket close down. I've spent hours looking at my application before conducting a simple test.

I took the sample code; https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/publish.html
commented out;
  if ((rc = MQTTAsync_disconnect(client, &opts)) != MQTTASYNC_SUCCESS)
        {
                printf("Failed to start sendMessage, return code %d\n", rc);
                exit(EXIT_FAILURE);
        }
and added a delay before the client closed down.

Results of test;
connlost function isn't fired
The trace reveals ExampleClientPub -> DISCONNECT (0) event as soon as I kill the connection.

I'm using the latest "master" branch on a debian raspberry pi (with the real time kernel patch) - 4.4.9-rt17+ #2 PREEMPT RT.

**Comment by icraggs** [comment]
The reason is that the setCallbacks call is not working.  If you check the return code, you'll see that it is not MQTTASYNC_SUCCESS.  The reason for that is that the messageArrived callback needs to be set.  I thought this should be compulsory, because what is the client library to do if a message does arrive?

That example needs to be updated.

**Comment by tropas2001** [comment]
Many thanks - will try later.
