### ISSUE TITLE
question: what is the purpose/handling of setting a token on subscribe options

### ISSUE THREAD

**Issue by tropas2001** [eclipse-paho/paho.mqtt.c#411]
The MQTTAsync_responseOptions structure allows for a token to be set however it's not clear in the documentation what this is / can be used for? 

I tried to set it with a value for a topic subscription (MQTTAsync_subscribe) however the resultant token which is passed back in the onSubscribe callback isn't this value. 

Is there a robust way of checking the success of a topic subscription when multiple subscriptions occur at the same time?

**Comment by icraggs** [comment]
Oh yes, the doc doesn't have a description - I'll fix that.  The token in the response options is returned, is not meant to be set.  It returns a value which can be used to tally with those in the callbacks and as input to the waitForCompletion call.  The value is actually the MQTT message id, which is why QoS 0 messages don't have one.

**Comment by tropas2001** [comment]
Thanks, so if I'm right in understanding if I'm using QoS 0 and request inspect the value of responseoptions.token I'll always get 0? If this is correct, I'm not sure I understand why QoS 0 don't have a message ID.

**Comment by icraggs** [comment]
That's what the MQTT specification says.  For QoS 0 there are no acks, so there is nothing to track with a message id.
