### ISSUE TITLE
Consider supporting only one build system

### ISSUE THREAD

**Issue by dawagner** [eclipse-paho/paho.mqtt.c#435]
There are two documented ways to build paho.mqtt.c (raw GNU Makefiles and CMake) and at least one undocumented way (Windows VC solution files). However, the travis and appveyor CIs only use CMake.

In my experience, it is difficult and painful to maintain multiple build systems in parallel, even more so when it is not regression-tested through CI. I would suggest sticking with CMake and get rid of the other build systems.

**Comment by JuergenKosel** [comment]
Hello,

we already have a similar discussion in pull request #148 , which request to add yet another build system: autoconf/automake. Because it provides better support for cross-compilation.

**Comment by icraggs** [comment]
I would certainly prefer to have one build system, but it's easier to add new ones than it is to remove old ones because someone seems to always prefer one or the other.

The first one that will go will be the Windows project files.  They are linked to a specific version of Visual Studio and a hard to maintain anyway.   Using CMake is far easier and it can generate Visual Studio projects (apparently - I've not tried it yet).

I like to keep the GNU make files because they still work and are easy to use.  As I get used to CMake more, or if they become hard to maintain then I might change my mind on that.

I quite like the idea of adding the auto-tools support, but it will take some learning time and effort on my part.  If I did that then the make files could be ditched, leaving us just with CMake and Autotools. Could be worse :-)
