### ISSUE TITLE
topic name is always empty

### ISSUE THREAD

**Issue by binbowang1987** [eclipse-paho/paho.mqtt.c#440]
when using paho.mqtt.cpp, I found that the topic name of consumed message is always empty. And I dig into the paho.mqtt.c source code, found this bug. 
![default](https://user-images.githubusercontent.com/8586061/38477720-cf41694c-3be6-11e8-8d25-9c1648690fc8.png)

version: paho.mqtt.c (1.2.0)

------------------------------------------
I change 'strlen(qe->topicName) == topicLen' to 'strlen(qe->topicName) != topicLen'. And the topic name is right now. Please fix it, Thanks.

**Comment by icraggs** [comment]
Hi.  This is intentional.  This is the description of the topic length field from the documentation (https://www.eclipse.org/paho/files/mqttdoc/MQTTAsync/html/_m_q_t_t_async_8h.html#a3918ead59b56816a8d7544def184e48e):

"The length of the topic if there are one more NULL characters embedded in topicName, otherwise topicLen is 0. If topicLen is 0, the value returned by strlen(topicName) can be trusted. If topicLen is greater than 0, the full topic name can be retrieved by accessing topicName as a byte array of length topicLen."

**Comment by fpagliughi** [comment]
Wait. What the....
How did I not catch this already?!?  This is definitely a bug in the C++ library. AND the Rust library! 
I will create an issue for each and get them fixed ASAP.

**Comment by fpagliughi** [comment]
I'll close this and move the discussion to the C++ and Rust libraries...

**Comment by icraggs** [comment]
As it happens, with the changes in the MQTT standard over the years, I'm not sure it's possible to get a null in the topic name any more.  The topic string is defined as a UTF-8 string, and null characters are explicitly forbidden.

**Comment by binbowang1987** [comment]
@icraggs  Hi, icraggs. I find in code file MQTTPacket.c in paho.mqtt.c, the '\0' is added. So ' strlen(topicName) == topicLen ' is always true.
![default](https://user-images.githubusercontent.com/8586061/38624603-101bd574-3ddb-11e8-9649-13776b9376bc.png)

![default](https://user-images.githubusercontent.com/8586061/38625151-6ac17e7e-3ddc-11e8-908e-f961e250b946.png)

@fpagliughi maybe this is an issue of paho.mqtt.c

**Comment by icraggs** [comment]
strlen(topicName) == topicLen could be false if there is a null character embedded within the topic string.  

As I said in my last comment I think is now forbidden by the MQTT specification, and so MQTT servers should not propagate such topic strings.  But that wasn't the case when I first wrote this code.

**Comment by binbowang1987** [comment]
Okay, I see. Thanks, icraggs.
