### ISSUE TITLE
[Android.mk] Outdated include paths and change to BorringSSL

### ISSUE THREAD

**Issue by sahillakhe** [eclipse-paho/paho.mqtt.c#444]
So when I try to compile for my Android Target device (Android O) I ran into the following problems:

1. external/hdc/android-ifaddrs \ and external/openssl/include no longer exist in the AOSP
2. android has changed from openssl to borringssl (almost exactly the same...but!)

What fixed it for me:
removed external/hdc/android-ifaddrs
edited: external/borringssl/include 

One possible consequence is I no longer needed the LOCAL_CFLAGS += -DOPENSSL. 

I guess the Android.mk needs to be updated ( Possibly also having the options for Android.bp ??) 
P:S. : This is my first ever issue reporting and I hope i have followed all guidelines.

**Comment by icraggs** [comment]
Thank you, your issue reporting is good :-)

I haven't personally used this client on Android, so that side of things is a bit of a black art for me.  I was expecting that the Java client would be the normal one to use on Android.

So Android is moving from OpenSSL to BoringSSL, and you had to make those changes to get it to work?  If you wish you could contribute your changes in a PR.

I see that Travis has support for Android projects (I just looked).  Ideally, then, we would have Travis CI tests for the Android environment, then I would be confident that any changes would work.

**Comment by icraggs** [comment]
No updates.
