### ISSUE TITLE
http client get/post request

### ISSUE THREAD

**Issue by sw-tt-chandershekharsuthar** [eclipse-paho/paho.mqtt.c#493]
how to use curl with paho mqtt.c projects  I want to get and post HTTP request I have windows7( 64bit )
working on visual studio 2017

**Comment by icraggs** [comment]
Hi.  Is this the same issue as you raised in #490 ?  I would appreciate it if you would continue the discussion in one issue, if this is indeed the same, rather than opening a new one.

I'm afraid I still don't understand what you want to do.  This client library is for MQTT, not HTTP.  I'm not sure how curl relates to it for your purpose.

**Comment by sw-tt-chandershekharsuthar** [comment]
hey icraggs,  Yes both are same issue for one task I want to 

.. Subscribe (mqtt sub) on some topics (on two topic TEST1 & test2) and saved data in a file
.. get some data with help of http get request(this is working).
.. do some logic (generating new data).
.. now I'm try to broadcast that updated data by MQTT publish(eclipse paho mqtt C)

both thing are working (in different 2 projects)
* when I tried to making new MQTT (PubSub) project with your library combine both of them that time is give me some errors like >>   client not connected, return code -1 but
* if I tried to modify your full project (eclips.paho.mqtt.c) which I installed by cmake in my system that time opened launch.vs.json file and stoped debugging and running project 

So I don't know may be its asking to modify that file or some change in that so tell me how to do that and what else will be helpful for me ...???
