### ISSUE TITLE
Mosquitto Keep Alive Timeout

### ISSUE THREAD

**Issue by jonface** [eclipse-paho/paho.mqtt.c#567]
Due to #513 , if the system clock is adjusted, possibly even slightly, it looks like the keep alive message fails to send ontime from paho, which causes mosquitto to disconnect the client.

I'd like to understand exactly why CLOCK_MONOTONIC is failing, as with my limited understanding, I've tried some simple tests using it and it seems to work as expected. 

Is there a simple, self contained example which would demonstrate CLOCK_MONOTONIC failing?

**Comment by icraggs** [comment]
There's example code in #513, but I don't think it's related to what you're seeing.

What OS are you using?  

START_TIME_TYPE MQTTAsync_start_clock(void)  starts a clock.
long MQTTAsync_elapsed(struct timeval start) returns the interval elapsed since the clock was started, which should be correct regardless of whether the system clock has changed.  By how much are you altering the system clock?

**Comment by icraggs** [comment]
I think this is done.
