### ISSUE TITLE
CMake: Bad OpenSSL include directory when cross-compiling

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [eclipse-paho/paho.mqtt.c#644]
I'm updating from paho.mqtt.c 1.1.0 to 1.3.0.
Thus I have to adjust our CMake calls. Instead of setting OPENSSL_INC_SEARCH_PATH and OPENSSL_LIB_SEARCH_PATH I now only use OPENSSL_SEARCH_PATH (in my example /foo/usr).
Now the libraries are found according to my search path, but a bad include directory is found. CMake picks up the host's OpenSSL include directory:

```
-- CMake version: 3.0.2
-- CMake system name: Linux
-- Timestamp is 2019-04-25T15:02:06Z
-- OpenSSL hints: /foo/usr
-- OpenSSL headers found at /usr/include
-- OpenSSL library found at /foo/usr/lib/libssl.so
-- OpenSSL Crypto library found at /foo/usr/lib/libcrypto.so
-- OpenSSL hints: /foo/usr
-- OpenSSL headers found at /usr/include
-- Configuring done
-- Generating done
```

As a consequence the build fails.

My workaround is using

`SET(OPENSSL_INCLUDE_DIR ${OPENSSL_SEARCH_PATH}/include)`

instead of

```
FIND_PATH(OPENSSL_INCLUDE_DIR openssl/ssl.h
        HINTS ${OPENSSL_SEARCH_PATH}/include)
```

Like this my build works, but of course only because I passed the OPENSSL_SEARCH_PATH to CMake. I'm pretty sure there is a clean CMake-ish way to get all cases to work cleanly.

This problem affects
src/CMakeLists.txt and test/CMakeLists.txt

**Comment by icraggs** [comment]
The OpenSSL settings for CMake has now changed to OPENSSL_ROOT_DIR.  I hope this is better.

**Comment by D-r-P-3-p-p-3-r** [comment]
Verified with 1.3.4: Works perfectly now when I'm using OPENSSL_ROOT_DIR.

**Comment by gfrigon** [comment]
I tried with 1.3.13. I get the following warning when setting OPENSSL_ROOT_DIR in CMAKE
```
CMake warning:
  Manually-Specified variables were not used by the project:

    OPENSSL_ROOT_DIR
```
Then the make fails later since <openssl/ssl.h> is not found

As a workaround, I added the following lines to `src/CMakeLists.txt`:
`include_directories(${OPENSSL_INC_SEARCH_PATH})`
`set(PAHO_OPENSSL_LIBRARIES "${OPENSSL_LIB_SEARCH_PATH}/libssl.so;${OPENSSL_LIB_SEARCH_PATH}/libcrypt.so")`

If I may add, the readme.md CMake Cross compile examples are still using OPENSSL_INC_SEARCH_PATH and OPENSSL_LIB_SEARCH_PATH instead of OPENSSL_ROOT_DIR
