### ISSUE TITLE
MQTTClient_publishMessage hangs waiting for a callback to return

### ISSUE THREAD

**Issue by sfindeisen** [eclipse-paho/paho.mqtt.c#685]
I am using `MQTTClient` in asynchronous mode (with `MQTTClient_setCallbacks`). It looks to me that `MQTTClient_publishMessage` hangs waiting for `MQTTClient_deliveryComplete` callback to return --- even though that is (of course) on a different thread.

I implemented a workaround for this in my application by restructuring the locks, but I think it would be nice if this limitation/feature was at least documented (if not fixed).

Unfortunately I cannot offer a minimal example at this point, nor a patch.

**Comment by fpagliughi** [comment]
A bug that may have lead to this problem was fixed and should be out in v1.3.1 within a few days. For now, try testing against the code in the 'develop' branch. Let us know if that doesn't fix the issue for you.

For more info see #657, #642, #596, and #637

**Comment by fire9953** [comment]
@fpagliughi  When can we get a new release? thanks.

**Comment by fpagliughi** [comment]
@yangke1120 I'm not the maintainer of this project, but was told that a release is coming soon.

**Comment by icraggs** [comment]
I've been debugging a problem which only shows up when building on Travis CI, only on the MacOS builds as they've got a lot slower recently.  It could well be #657.  Slow to debug as I have to run the Travis build with debug output on.  I just wanted to get this one done before releasing.

**Comment by dpostorivo** [comment]
@icraggs sorry to butt in, but the MacOS Build seems to be slower due to the `before_install.2`
which takes a whopping 765 seconds.

The actual build step takes 368.23s for linux and for MacOS takes 390.42s which isn't a huge difference in terms of execution for a 5+ minute build between two jobs. 

Travis does tend to update their images which can cause setup oddites like this.

**Comment by icraggs** [comment]
@dpostorivo This is true.  However the CI tests for MacOS also used to run cleanly much more often than not.  Since this change, the tests are failing much more frequently.  That seems to be down to exposing inherent bugs as a result of the change of timing, whatever the cause.  It could be a good thing in that it allows those bugs to be found and fixed (even running the tests on a Raspberry Pi failed to show the bugs).

**Comment by icraggs** [comment]
1.3.1 was released in August 2019.  I hope this issue is fixed.
