### ISSUE TITLE
CPU usage goes to 100%

### ISSUE THREAD

**Issue by jovanz** [eclipse-paho/paho.mqtt.c#734]
We have an issue with Paho C client on Linux platform, version of Paho library is 1.3.1. When the client connects after one failed connection, CPU usage goes to 100%.

Steps to reproduce issue:
Disable broker
Client failed to connect to broker
Enable broker
Client successfully connects to broker
Then CPU usage will go to 100% for client application

I submited new test https://github.com/jovanz/paho.mqtt.c/commit/68c425cb7bf0c81e4b22d83e3f0c91fc690c1963, 
please check if it can help you to reproduce the issue.

If we revert commit "Correct state changes in MQTTClient.c eclipse#604" https://github.com/jovanz/paho.mqtt.c/commit/d01fa1cce9188604b216b85912f016b05bf86649, this issue doesn't occure.

In attachment is log file.
[test_reconnect.txt](https://github.com/eclipse/paho.mqtt.c/files/3652416/test_reconnect.txt)

**Comment by LorenzoBe** [comment]
I would also be interested in this issue, because we had the same 100% CPU usage when we run it on devices which has just one core (Windows Embedded Compact 7) or we run tests on Linux machines using Valgrind (which forces the queueing of threads, disabling parallel execution).
The problem is that when the connection fails, Paho thread continuously call the MQTTClient_run(void* n) function in MQTTClient.c, exiting just after some checks because a connection is still not there.
But unfortunately the connection thread cannot be executed because it is not able to get the required lock on a mutex, preempting the other thread. This also depends on the goodnes of the OS scheduler.
As a dirty fix, we added a MQTTClient_sleep in MQTTClient_run(void* n) function, you can see it here:
```
/* This is the thread function that handles the calling of callback functions if set */
static thread_return_type WINAPI MQTTClient_run(void* n)
{
        long timeout = 10L; /* first time in we have a small timeout.  Gets things started more quickly */

        FUNC_ENTRY;
        running = 1;
        run_id = Thread_getid();

        Thread_lock_mutex(mqttclient_mutex);
        while (!tostop && initialized)
        {
                int rc = SOCKET_ERROR;
                int sock = -1;
                MQTTClients* m = NULL;
                MQTTPacket* pack = NULL;

                Thread_unlock_mutex(mqttclient_mutex);
                // this sleep allows concurrent threads to acquire mqttclient_mutex, especially on
                // single core devices or on constrained run (e.g. Valgrind on Linux)
                MQTTClient_sleep(1L);
                pack = MQTTClient_cycle(&sock, timeout, &rc);
                Thread_lock_mutex(mqttclient_mutex);
                if (tostop || !initialized)
                        break;
```

This fixed the behaviour, but not the real issue.
I don't know your Paho version, but I hope this will also fit to your code. It should not heavily impact the performances because the sleep is executed just when we are attempting to connect.

**Comment by zhaoxianpeng** [comment]
I met the similar issue. resolve it by calling MQTTClient_disconnect  in the callback function of lose connection.
When the network is unstable, the connection maybe lose.
you should call MQTTClient_disconnect in the callback function of lose connection to close the unused socket avoid the issue.

**Comment by jovanz** [comment]
In test case we call MQTTClient_disconnect if connection failed. Connection failed is mandatory to reproduce this issue, if client connect on first attempt CPU doesn't go up to 100%.

**Comment by zhaoxianpeng** [comment]
the root cause is receiving a packet from the socket which belong to a client which had been destroied.
a socket always in the select list before disconnect, even the client belong to have been destroied,
Since the client have been destroied, no one to handle the data in the socket, so the select will return without any wait in every loop, but after the return, no one read the data in the sokcet then enter the next loop, it caused the CPU load high.

I resolve it by calling a MQTTClient_disconnect to close the socket safely when find a connect lost happened.

**Comment by DiegoDotti** [comment]
Hello! I'm also using  c# library on windows ce7 and I also have the 100% cpu problem.
I'm using the library in the following link https://github.com/eclipse/paho.mqtt.m2mqtt/blob/master/M2Mqtt/MqttClient.cs, but I don't know where to put the client disconnection in case of connection failure.
Could someone kindly help me?

thanks a lot

**Comment by DiegoDotti** [comment]
Hi! Your solutions concern the project written in c and not in c #. I can't find this solution in c#.
Help me, please.
