### ISSUE TITLE
Memory overflow for message arrived when user forget to set callback?

### ISSUE THREAD

**Issue by Doawen** [eclipse-paho/paho.mqtt.c#748]
in line 2224 for routine 'MQTTAsync_receiveThread',code is :
				if (strlen(qe->topicName) == topicLen)
					topicLen = 0;

				if (m->ma)
					rc = MQTTAsync_deliverMessage(m, qe->topicName, topicLen, qe->msg);
				else
					rc = 1;
				if (rc)
				{
#if !defined(NO_PERSISTENCE)
					if (m->c->persistence)
						MQTTPersistence_unpersistQueueEntry(m->c, (MQTTPersistence_qEntry*)qe);
#endif
					ListRemove(m->c->messageQueue, qe); /* qe is freed here */
				}
				else
					Log(TRACE_MIN, -1, "False returned from messageArrived for client %s, message remains on queue",
						m->c->clientID);

I have two question:
1,when user forget to set 'm->ma', then rc = 1 and call "ListRemove",the code forget to free room for "qe->topicName"and "qe->msg"。when user set "m->ma", we assume that user must call "MQTTAsync_freeMessage(&message); MQTTAsync_free(topicName);" corectly. why we do not set this two line in our library and call these whenouter from "m->ma" routine？ I think this is a better one. Do you think?
2. Why set topicLen to 0 when strlen(qe->topicName) == topicLen? I don't know. now I know the reason from "MQTTAsync_messageArrived" definition, but I think should add this code to routine "Protocol_processPublication" line 2812 ?

thank you for reading.

**Comment by icraggs** [comment]
1) Yes, there is probably an issue when messageArrived is not set.  The general approach is to say that you should always set the messageArrived callback otherwise you won't know if any message arrives.  I'd prefer to enforce that, probably.

The reason for not automatically freeing the message storage is that  the application might want to handle the message later, just storing the pointers.  

2) Having a non-zero topic length indicates that strlen() isn't going to work, likely because of embedded nulls.

**Comment by icraggs** [comment]
Add some doc, and an error in the trace if a message arrives and no message arrived callback is set.
