### ISSUE TITLE
internal symbols are exported on linux

### ISSUE THREAD

**Issue by mvduin** [eclipse-paho/paho.mqtt.c#794]
On linux, the shared libraries do not just export symbols which are supposed to be exported but also tons of internal symbols, some of which can very easily conflict with other libraries or user programs, e.g. "state", "writeInt", "Log", and "SHA1_Update".

Please ensure that code is compiled with -fvisbility=hidden and add suitable attributes to declarations of symbols that need to be exported. See https://gcc.gnu.org/wiki/Visibility for details.

**Comment by icraggs** [comment]
I assume you mean in the CMake build.  This has been in the Makefile build for years but not all the features of that were duplicated in the CMake contribution.

**Comment by mvduin** [comment]
when using cmake yes.  I wasn't aware that this was a "second-tier" (poorly tested) way of building the library, perhaps the readme should make this clear

**Comment by icraggs** [comment]
Well I wouldn't quite phrase it as poorly tested, as the CMake builds are using in the Travis and AppVeyor CI tests.  I did create the Makefile build, and the CMake build was contributed afterwards.  It did make it a lot easier to support building on Windows though :-)

Still with this addition and one other for the initialization, then I think all the bases will have been covered.  Thanks for pointing it out.

**Comment by waltronix** [comment]
I can have a look here.

There are two definitions for exporting stuff that I would merge into one and provide via an extra header file.

So it is:
* LIBMQTT_API
* DLLExport

**Comment by fpagliughi** [comment]
I wonder if it's time to obsolete the Makefile build, upgrade the CMake one to a more "modern" version of CMake, and use that as the one supported build system. I've spent a good amount of time on Issue reports this year that turned out to be subtle differences in the library produced by the different build systems. 

Unfortunately, my CMake skills are still a bit lacking to be a lot of help, but I'm working on it. (BTW, Craig Scott's "Professional CMake" is well worth the money; I'm working my way through it right now. https://crascit.com/professional-cmake/)

**Comment by waltronix** [comment]
If there is no system that requires the pure Makefiles, I agree.

But I would start by tackling the remaining build issues step by step, cleaning the CMakeLists a bit and updating CI builds before removing anything anyhow.

**Comment by icraggs** [comment]
Ok.  Develop branch.  A recent PR changed the DLLExport definitions to LIBMQTT_API, but evidently now I look, it missed the MQTTProperties and MQTTReasonCodes header files.   They should be using the LIBMQTT_API definition.

I'm not sure about requiring a more modern version of CMake.  Won't someone come along and say their system doesn't support it?  

I'm also not sure about deprecating the Makefile - at least not yet.  That's the one I created and it's more transparent than the CMake configs.  It's also, at the moment, the definitive build for Linux/MacOS until the CMake one catches up.

The CMake build needs to add a number of features which are in the Makefile - symbol visibility, shared library initialization being the main two.  I had assumed that the contributed CMake build had duplicated the Makefile setup, but evidently that was incorrect, event tho the CI tests passed.  So the first step is to ensure that the CMake build duplicates the features of the Makefile builds, particularly on Linux and MacOS.

**Comment by waltronix** [comment]
So, I will give my best to bring the cmake stuff up to the makefiles level in the next time.

**Comment by icraggs** [comment]
@waltronix Thank you!  I would appreciate that very much.  If you have any questions, please ask.

**Comment by fpagliughi** [comment]
@icraggs Yes, I assume anytime we upgrade tools someone will complain. But I'm advocating for a version of CMake that came out, say, within the last 5-6years! (Maybe >= 3.2)?

The transition from the CMake 2.8 to 3.x versions was pretty major, marking what those folks are calling "Modern" CMake. There is much better per-project encapsulation of the build rules, which really helps include libraries like this into bigger builds.

Keep in mind, too, that you generally need a version of CMake that is newer than the tools and platforms that you're targeting. So I think people generally upgrade. And it's pretty easy, and versions remain backward-compatible, so it doesn't break old builds to upgrade.

The Paho C++ library required an upgrade a while back in order to support newer compiler flags. I put up some instructions for the (then) current versions of Ubuntu. No one complained.
https://github.com/eclipse/paho.mqtt.cpp/#updating-cmake-on-ubuntu-1404-or-1604

**Comment by waltronix** [comment]
Would debian be a good source for a minimum cmake version?
When searching the package sources, I found that oldstable provides cmake 3.7, with backports even 3.13.

https://packages.debian.org/search?keywords=cmake

**Comment by fpagliughi** [comment]
Yeah, Debian is a good reference. Ubuntu LTS on top of it too. The oldest supported LTS, Ubuntu 16.04 is Debian 9/stretch, I believe, using a 2.8 cmake. The next one, Ubuntu 18.04 (buster), jumped to cmake 3.10.

Looking at features...
 - CMake v3.5 Added improved support for finding OpenSSL on Windows.
 - CMake v3.7 Improved on find_library() and find_package()
etc...

So perhaps v3.5 is the minimum we should consider. Maybe that should be it unless there's a good reason to pick something newer. Some specific feature that would be a "must have".

**Comment by fpagliughi** [comment]
Ha. My personal notes are mostly "write only" memory, but I stumbled on this, dated a year ago:

>  • Any project or tutorial requiring CMake < v3.5 should be considered suspect. 
>  • Anything requiring CMake < v3.1 should just be ignored.

So I reiterate my previous comment!

**Comment by icraggs** [comment]
I think this is fixed in the develop branch with the merge of #798
