### ISSUE TITLE
i have an issue about MQTT，but it is not a bug.

### ISSUE THREAD

**Issue by guoyanzhang0817** [eclipse-paho/paho.mqtt.c#888]
when QOS is 2, whether the broker will store a message and  message id from the publisher or just message id?
I read some materials and said that broker only stores ID. So when the subscriber subscribes, the broker requests a message from the publisher according to the stored message id, then the publisher sends a message to the broker, and the broker forwards it to the subscriber. Is that so?

**Comment by icraggs** [comment]
A message id is only valid between one client and a broker in one direction, and is only used to ensure the correct delivery of QoS 1 and 2 messages (QoS 0 messages have no message id).  Once the broker has stored a message safely, the QoS 2 packet exchange being complete, there is no longer any association with the incoming message id.  It is associated with a topic, not a message id.

When the message is stored, the broker works out what subscribers there are to the topic, and forwards the message on to those subscribers, using new message ids for each.  Each subscriber/broker pair will be using an independent new message id.

When a subscriber connects to a broker, the broker does not request messages from publishers.  It is entirely a push model - when a publisher decides to send a message, it is forwarded to all current subscribers.

It might be easier to see what is going on by using the broker in https://eclipse/paho.mqtt.testing because it is written in python and if you use the debug log level you can see all the MQTT packets as they are sent and received.

**Comment by guoyanzhang0817** [comment]
> A message id is only valid between one client and a broker in one direction, and is only used to ensure

Thank you very much for your answer
