### ISSUE TITLE
Remove redundancy from Secure MQTT implementation

### ISSUE THREAD

**Issue by bryant-ferguson** [eclipse-paho/paho.mqtt.c#899]
**Is your feature request related to a problem? Please describe.**
I inherited a project that uses this library for MQTT and am adding TLS support to the project.
So, I went about configuring the "sslOptions" struct. It didn't work. I looked at mosquitto broker logs, and wireshark traces and was baffled by the client sending information in plaintext, but wireshark identifying it as an SSL packet. I tried every configuration I could imagine. I wasted multiple days consulting with co-workers trying to figure out what was wrong with my configuration -- I looked through Paho C changelogs and bug reports and thought I found some related bugs, so I upgraded to the newest version -- no change. 

Then I found that you have to prefix the hostname with "ssl" instead of "tcp". I was furious that it was such a simple thing. This seems unnecessary and doesn't make much sense as SSL/TLS is layered on TCP. There were not indications of this mismatch in the ssl call back or connection failure call back. There is no documentation on the sslOptions page that this is necessary. Even the README doesn't say anything about this; for the purposes of setting up tests it just says that the secure server defaults to "localhost". Furthermore, if you configure sslOptions for server authentication, you can still connect unwittingly to an unsecured broker and Paho connects with no complaints from Paho if you don't set the hostname prefix to ssl. 

**Describe the solution you'd like**
Remove the prefix requirement for the hostname. This coupling is code smell and makes for difficult to maintain code. At the very least, the documentation for the sslOptions object should indicate that you also need to change the protocol prefix on the hostname and useful errors should be returned. 

**Describe alternatives you've considered**
I can just workaround it, but I can only imagine how many hours have been wasted by others trying to figure this out. Perhaps there is a good reason for the implementation being the way it is, but it's not user friendly.

**Comment by fpagliughi** [comment]
But what if you're using a different secure protocol that requires the SSL options, like secure websockets?  `wss://...`

**Comment by jumoog** [comment]
I had that problem too. Without ssl options it is tcp or else it is ssl. If you want websocket you have to specify that. I have integrated this logic into my application.

**Comment by icraggs** [comment]
I'm sorry to hear that you spent so much time working this out.

History: the 'URI' type connection info was chosen when I was working at IBM in the mid 2000s.  This wasn't the only client library that used that convention, and I don't remember much about the discussions.  I do remember we considered using 'mqtt' as a prefix: mqtt://mqtt.eclipse.org:1883 but ultimately decided against it.  So, it's been like that for >10 years, and I haven't given it much (any) thought since.

As Frank points out, there are now websockets options too, and others could conceivably exist, such as Unix sockets or other IPC mechanisms, if you wanted to do such a thing.  These other options may or may not use SSL themselves too.

The doc for serverURI does mention the ssl prefix, although it didn't mention the websockets options (I'll fix that).  I will also add information to the SSLOptions structure to emphasize the point that the serverURI needs to use one of (ssl, wss) prefixes to activate them.

If there are any other suggestions for making this clear, do suggest them.

**Comment by bryant-ferguson** [comment]
Thanks for providing some background. I submitted this ticket while pretty frustrated, so thanks for bearing with me. 

I think the least work for the most pay off is just adding some notes to the SSL options struct docs. Thanks.

**Comment by fpagliughi** [comment]
I'm fine with the URI dictating the connection type. That's common enough. And, sure, the documentation could be improved. A pull request on the docs from someone coming at the project for the first time would be really useful, since they would have a fresh perspective on what is lacking. 

But I do feel for someone new getting caught up on something that should be more obvious. Could the connect call return an error if you provide SSL options with a non-secure transport?  Is there a reason that we couldn't do that? It's likely a breaking change, but might be helpful.

**Comment by icraggs** [comment]
Yes it would be a breaking change which I wouldn't want to do without bumping the major version number.  I've added some info/warnings to the doc for this release.
