### ISSUE TITLE
How to know if multiple subscriptions have succeeded?

### ISSUE THREAD

**Issue by nirmitdesai** [eclipse-paho/paho.mqtt.c#910]
I use MQTTAsync_subscribeMany to subscribe to multiple topics. If I get onSuccess callback, does it mean that all the topics have been successfully subscribed to? Is it possible for any one topic to fail on subscription? 

Lastly, what's the difference between getting MQTT_ASYNC_SUCCESS return code from MQTTAsync_subscribeMany and getting the onSuccess callback?

**Comment by icraggs** [comment]
As described in the [MQTT 3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718067) each topic in the subscribe has a corresponding return code in the SUBACK packet.  The return code is either the maximum QoS that was granted, or the error code showing that the subscription to that particular topic failed.

Each of these return codes is passed back in the onSucess callback qosList field. It will always be the onSuccess callback even if all the subscriptions failed, because that seems like an uncomfortable distinction to make, and in the vast majority of cases, subscriptions will succeed.

**Comment by nirmitdesai** [comment]
Thanks for the reply. But if the return code incase of error is in onSuccess callback, what is use of onFailure callback?

**Comment by icraggs** [comment]
onFailure: 
- if there is one subscription (the majority of cases) and that gets a fail return code
- if the connection fails before the suback is received

**Comment by icraggs** [comment]
It's not perfect, but then error reporting is not perfect in MQTT 3.1.1, which is why we improved it in MQTT 5.0.
