### ISSUE TITLE
ALPN support for aws iot

### ISSUE THREAD

**Issue by Ami-P** [eclipse-paho/paho.mqtt.c#936]
How do I set ALPN as described here for the python version of this library
https://aws.amazon.com/blogs/iot/how-to-implement-mqtt-with-tls-client-authentication-on-port-443-from-client-devices-python/

thanks in advance

**Comment by icraggs** [comment]
You can't, as it stands, except if you change the source code.  It's the first time I've heard of this requirement.  I'm open to PRs (along with tests) if anyone gets to it before I do.

The relevant section of the OpenSSL API: https://www.openssl.org/docs/man1.1.0/man3/SSL_set_alpn_protos.html

One way to implement this would be to accept or return an SSL context object so that any other manipulations on the context object could be done by the application.

**Comment by Ami-P** [comment]
opened pull request
https://github.com/eclipse/paho.mqtt.c/pull/938
