### ISSUE TITLE
onSuccess callback function is not triggered when reconnect to the broker automatically

### ISSUE THREAD

**Issue by rqg0717** [eclipse-paho/paho.mqtt.c#943]
Using Paho MQTT C Lib version 1.3.5, MQTTAsync_connect sets callback functions including onSuccess = onConnect; and automaticReconnect set to 1.
onConnect function can be called on the first successful connection; however, after lost connection and reconnected to the broker, onConnect function was not triggered thus it was not able to resubscribe the topic.
onConnect function:
```
static void onConnect( void* context, MQTTAsync_successData* response ) {
   int rc = -1;
   MQTTAsync client = (MQTTAsync) context;
   if (opts.verbose)
      printf( "Subscribing to topic %s with client %s at QoS %d\n", opts.topic, opts.clientid, opts.qos );
   ropts.context = client;
   if ((rc = MQTTAsync_subscribe( client, opts.topic, opts.qos, &ropts )) != MQTTASYNC_SUCCESS) {
      if (!opts.quiet)
         fprintf( stderr, "Failed to start subscribe, return code %s\n", MQTTAsync_strerror( rc ) );
   }
}
```

**Environment (please complete the following information):**
 - OS: Ubutnu 14.04
 - Version libpaho-mqtt3as 1.3.5

**Additional context**
log:
Connecting to wss://127.0.0.1:443 ... 
Connect to MQTT broker, return code: Success. 
Subscribing to topic /test with client CLIENTID_0_1598979517 at QoS 2
onConnectFailure: Connect failed, rc Failure reason code socket error
onConnectFailure: Connect failed, rc Failure reason code TCP connect completion failure
onPublishFailure: Publish failed, rc Operation discarded before completion.

**Comment by icraggs** [comment]
The onSuccess or onFailure callbacks are called once per operation only.

This is the documentation for the MQTTAsync_connected callback:

 This is a callback function, which will be called when the client
 library successfully connects.  This is superfluous when the connection
 is made in response to a MQTTAsync_connect call, because the onSuccess
 callback can be used.  It is intended for use when automatic reconnect
 is enabled, so that when a reconnection attempt succeeds in the background,
 the application is notified and can take any required actions.

 <b>Note:</b> Neither MQTTAsync_create() nor MQTTAsync_destroy() should be
 called within this callback.
 @param context A pointer to the <i>context</i> value originally passed to
 MQTTAsync_setCallbacks(), which contains any application-specific context.
 @param cause The reason for the disconnection.
 Currently, <i>cause</i> is always set to NULL.

typedef void MQTTAsync_connected(void* context, char* cause);

Use MQTTAsync_setConnected() to set it.

**Comment by rqg0717** [comment]
@icraggs Thanks a lot for your detailed response. That's exactly what I need.
