### ISSUE TITLE
Race between MQTTClient_subscribe and message_arrived causes use after free

### ISSUE THREAD

**Issue by RelayrMA** [eclipse-paho/paho.mqtt.c#995]
**Describe the bug**
My application is crashing under stress tests with valgrind. I see it's a race because sometimes the subscribe thread crashes on memory freed by message_arrived and sometimes it's the other way around. Also, sometimes there is no crash, the application works fine.

**To Reproduce**
I don't have a simple test case, it would take a while to trim my application this small. But I can try make it if necessary.
The basic scenario is:
* bombard the broker with a stream of messages published as fast as I can
* subscribe my application to that stream of publications
* make several more subsciptions

At one point the application crashes.
I notice that paho seems to be mostly occupied with handling the incoming messages and is very slow at processing my subscriptions, it takes seconds to make each.
In wireshark I see that before the crash there's a number of warnings about TCP window being full.

Trace level logs as well as a wireshark dump can be found here:
[logs.zip](https://github.com/eclipse/paho.mqtt.c/files/5499809/logs.zip)

**Expected behavior**
The code doesn't crash

** Environment:**
 - OS: Gentoo
 - Version 1.3.6

**Comment by icraggs** [comment]
About the time to process subscriptions first.  If you are receiving a continuous stream of QoS 0 messages, then the response from the subscribe (suback) is going to be queued up behind those so a delay is not surprising.  It's easy to overload brokers and clients with QoS 0 messages as there is no flow control except for filling up TCP buffers.

Secondly, you appear to have connected with MQTT cleansession.  Your problem is caused by the subscribe getting an error on the TCP socket, presumably as a result of the TCP buffers filling up.  This results in the connection being broken, and as you have connected cleansession, all the state including messages for that client is being cleaned up while your application is processing the incoming message.

Looks like there's a lock and checks that can be added to MQTTClient_freeMessage.  But what do you expect to happen after filling up the TCP buffers and causing a socket error (maybe there's a broker error too)?

**Comment by RelayrMA** [comment]
I've tried registering subscriptions with the client before connecting to the broker. It didn't solve the issue.
Yes, we're using clean session.
I tried looking at the issue with strace to see any socket errors but as soon as I connect it, the issue disappears.

What do I expect after filling up TCP? I don't know, depends on what kind of error is it. Maybe a re-trial? Reporting an error to the user would be fair as well but what could I do other than retry?

Any broker issue should be visible in the tcpdump, right?

**Comment by icraggs** [comment]
If you're expecting messages to be retried after a disconnect/reconnect due to TCP buffers filling up then connecting cleansession=true is not a good idea as it causes all the state for that client to be discarded on the socket error/disconnect.

I wouldn't expect any broker error to be visible in the TCP dump, no.  The socket close, yes.  But the reason for the broker closing the session with the client, no.  You could be exceeding the allowed parameters of the MQTT session, if there are any (message rate, etc), or the TCP buffers filling up might cause a backlog of messages on the server which it doesn't like.  Those are a couple of examples I can think of.

**Comment by RelayrMA** [comment]
I don't care about the loss of QoS 0 messages, regardless of what happens with the connection. They can be discarded.
We may need to use clean session = false for other reasons, though it causes us some problems. So it seems like we won't be affected by this bug by the time we reach production.

Anyway, it seems to me like the client is the side that closes session, not the broker. It sends the disconnect, it closes the stream.

**Comment by icraggs** [comment]
Oh yes, that's because of the command timeout for subscribe and unsubscribe which was set to an arbitrary 10 seconds.  That was done because the MQTTClient API was intended for simple, low volume scenarios.  I've just added the means to change that timeout in the develop branch, as that had been requested before anyway.

**Comment by icraggs** [comment]
So, I don't know whether you're up for trying something out for me by changing the source code?  If so, comment out the 

    Thread_unlock_mutex(mqttclient_mutex);

and

    Thread_lock_mutex(mqttclient_mutex);

lines in MQTTClient.c (lines 855 and 857 in the master branch) - the ones that surround the call to message arrived:

    rc = (*(m->ma))(m->context, qe->topicName, topicLen, qe->msg);

That should stop the subscribe interfering with the message arrived processing.

**Comment by icraggs** [comment]
Command timeout setting added in #673.

Message arrived protection being dealt with in #1009.
